apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner
spec:
  selector:
    matchLabels:
      app: partner
  template:
    metadata:
      labels:
        app: partner
        component: workload
    spec:
      containers:
      - image: ghcr.io/jobscale/partner
        name: partner
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: partner
spec:
  selector:
    app: partner
  type: LoadBalancer
  ports:
  - name: tls
    port: 443
    protocol: TCP
    targetPort: 443
