#!/usr/bin/env bash
set -eu

# chrome apps 68
# code 28

additional=${1:-0}

adjust-window() {
  read -r WIDTH HEIGHT _ < <(xdotool getdisplaygeometry)

  top=0
  [[ $(hostname) == 'bookworm' ]] && top = 272
  height=$(( HEIGHT + additional - top ))
  left=0
  width=$(( WIDTH + additional ))
  [[ $width > 1200 ]] && width=$(( width / 2 ))

  WIN=$(xdotool getactivewindow)

  xdotool windowsize "$WIN" $width $height
  xdotool windowmove "$WIN" $left $top
  xdotool getwindowgeometry --shell "$WIN"
  echo " via $(xdotool getdisplaygeometry)"
}

adjust-window | xargs
