#!/usr/bin/env bash
set -eu

# chrome apps 68
# code 28

additional=${1:-0}

adjust-window() {
  WIN=$1
  read -r WIDTH HEIGHT _ < <(xdotool getdisplaygeometry)
  top=$(( additional / -2 ))
  [[ $(hostname) == 'bookworm' ]] && top=$(( 272 ))
  height=$(( HEIGHT + additional - top ))
  left=$(( additional / -2 ))
  width=$(( WIDTH + additional ))
  [[ $width -gt 1400 ]] && width=$(( width / 2 ))

  xdotool windowsize "$WIN" $width $height
  xdotool windowmove "$WIN" $left $top
  xdotool getwindowgeometry --shell "$WIN"
  echo " via $(xdotool getdisplaygeometry)"
}

show-process() {
  WIN=$1
  TITLE=$(xdotool getwindowname "$WIN")
  PID=$(xprop -id "$WIN" _NET_WM_PID | awk '{print $3}')
  CMD=$(ps -p "$PID" -o comm=)

  echo "Title: $TITLE"
  echo "Command: $CMD"
}

main() {
  local WIN=$(xdotool getactivewindow)
  adjust-window $WIN | xargs
  show-process $WIN
}

main
