---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
  labels:
    app: bind9
    component: deployment
spec:
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
        component: workload
    spec:
      containers:
      - name: bind9
        image: ghcr.io/jobscale/bind9
---
apiVersion: v1
kind: Service
metadata:
  name: bind9
  labels:
    app: bind9
    component: service
spec:
  selector:
    app: bind9
  type: LoadBalancer
  ports:
  - name: udp
    nodePort: 30053
    port: 53
    targetPort: 53
    protocol: UDP
  - name: tcp
    nodePort: 30053
    port: 53
    targetPort: 53
    protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bind9
  labels:
    app: bind9
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bind9
  maxReplicas: 20
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
