apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-lo
  labels:
    app: next-lo
    component: deployment
spec:
  selector:
    matchLabels:
      app: next-lo
  template:
    metadata:
      labels:
        app: next-lo
        component: workload
    spec:
      containers:
      - image: ghcr.io/jobscale/reverse-proxy
        name: next-lo
        env:
        - name: BACKEND
          value: http://next.proxy.jsx.jp:3458
---
apiVersion: v1
kind: Service
metadata:
  name: next-lo
  labels:
    app: next-lo
    component: service
spec:
  selector:
    app: next-lo
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: next-lo
  labels:
    name: next-lo
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - secret'
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: [ "next.jsx.jp", "next.x.jsx.jp" ]
  rules:
  - host: next.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: next-lo
            port:
              number: 80
  - host: next.x.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: next-lo
            port:
              number: 80
