#!/usr/bin/env bash

web() {
  loadImage ghcr.io/jobscale/web
  kubectl rollout restart deployment -n default web
  echo https://web.jsx.jp
}

jsxjp() {
  loadImage ghcr.io/jobscale/jsxjp
  kubectl rollout restart deployment -n jsxjp jsxjp
  echo https://jsx.jp
}

tanpo() {
  loadImage ghcr.io/jobscale/tanpo
  kubectl rollout restart deployment -n standard tanpo
  echo https://tanpo.jsx.jp
}

dns-nodejs() {
  loadImage ghcr.io/jobscale/dns-nodejs
  kubectl rollout restart deployment -n net-apps dns-nodejs
}

bind9() {
  loadImage ghcr.io/jobscale/bind9
  kubectl rollout restart deployment -n net-apps bind9
}

squid() {
  loadImage ghcr.io/jobscale/squid:secure
  kubectl rollout restart deployment -n net-apps squid
}

nodeAws() {
  loadImage ghcr.io/jobscale/node-aws:dind
  kubectl rollout restart deployment -n standard node-aws
}

codeServer() {
  loadImage ghcr.io/jobscale/code-server
  kubectl rollout restart deployment -n standard code-server
  echo https://code-server.jsx.jp
}

wetty() {
  loadImage ghcr.io/jobscale/wetty:dind
  kubectl rollout restart deployment -n wetty wetty
  echo https://wetty.jsx.jp/wetty
}

sshwifty() {
  loadImage ghcr.io/jobscale/sshwifty
  kubectl rollout restart deployment -n standard sshwifty
  echo https://sshwifty.jsx.jp
}

zipcode() {
  loadImage ghcr.io/jobscale/zipcode-jp
  kubectl rollout restart deployment -n standard zipcode-jp
  echo https://zipcode-jp.jsx.jp
}

mqtt() {
  loadImage ghcr.io/jobscale/mqtt-c-pub-sub
  kubectl rollout restart deployment -n standard mqtt
  echo https://mqtt.jsx.jp
}

partner() {
  kubectl rollout restart deployment -n credentials partner
}

cronJob() {
  loadImage ghcr.io/jobscale/kabuka
  loadImage ghcr.io/jobscale/news-top
  loadImage ghcr.io/jobscale/info-certificate
  loadImage ghcr.io/jobscale/speedtest
}

loadImage() {
  time {
    docker pull $1
    kind load docker-image $1 --name ${CLUSTER_NAME:-production}
  } | xargs echo -n
  echo
}

pullImage() {
  time {
    docker exec -i ${CLUSTER_NAME:-production}-control-plane crictl pull $i
  } | xargs echo -n
  echo
}

{
  THIS=${0##*/}
  grep ^[a-z] rollout | awk -F'(' '{print $1}'
}
