#!/usr/bin/env bash

web() {
  docker exec -it ${ENV:-production}-control-plane crictl pull ghcr.io/jobscale/web
  kubectl rollout restart deployment -n default web
}

jsxjp() {
  docker exec -it ${ENV:-production}-control-plane crictl pull ghcr.io/jobscale/jsxjp
  kubectl rollout restart deployment -n jsxjp jsxjp
}

tanpo() {
  docker exec -it ${ENV:-production}-control-plane crictl pull ghcr.io/jobscale/tanpo
  kubectl rollout restart deployment -n standard tanpo
}

bind9() {
  docker exec -it ${ENV:-production}-control-plane crictl pull ghcr.io/jobscale/bind9
  kubectl rollout restart deployment -n net-apps bind9
}

squid() {
  docker exec -it ${ENV:-production}-control-plane crictl pull ghcr.io/jobscale/squid:secure
  kubectl rollout restart deployment -n net-apps squid
}

nodeAws() {
  docker exec -it ${ENV:-production}-control-plane crictl pull ghcr.io/jobscale/node-aws:dind
  kubectl rollout restart deployment -n standard node-aws
}

codeServer() {
  docker exec -it ${ENV:-production}-control-plane crictl pull ghcr.io/jobscale/code-server
  kubectl rollout restart deployment -n standard code-server
}

wetty() {
  docker exec -it ${ENV:-production}-control-plane crictl pull ghcr.io/jobscale/wetty:dind
  kubectl rollout restart deployment -n standard wetty
}

mqtt() {
  docker exec -it ${ENV:-production}-control-plane crictl pull ghcr.io/jobscale/mqtt-c-pub-sub
  kubectl rollout restart deployment -n standard mqtt
}

partner() {
  kubectl rollout restart deployment -n credentials partner
}

{
  THIS=${0##*/}
  grep ^[a-z] rollout | awk -F'(' '{print $1}'
}
