apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-server-pv
spec:
  storageClassName: ssd.sda
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/extra/home/store"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code-server-pv-claim
spec:
  storageClassName: ssd.sda
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - image: ghcr.io/jobscale/code-server:dind
        name: code-server
        securityContext:
          privileged: true
        volumeMounts:
        - name: code-server-persistent-storage
          mountPath: /home/store
      volumes:
      - name: code-server-persistent-storage
        persistentVolumeClaim:
          claimName: code-server-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
spec:
  selector:
    app: code-server
  type: ClusterIP
  ports:
  - name: tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
