#!/usr/bin/env bash

adminDashboard() {
  DASHBOARD_VERSION=$(
    git ls-remote --refs --tags https://github.com/kubernetes/dashboard.git | grep tags/v | sort -t '/' -k 3 -V | grep -v alpha | tail -1 | awk -F/ '{print $3}'
  )
  echo -e "\n Kubernetes Dashboard ${DASHBOARD_VERSION} \n"
  curl -so dashboard/kubernetes-dashboard.yaml https://raw.githubusercontent.com/kubernetes/dashboard/${DASHBOARD_VERSION}/aio/deploy/recommended.yaml
  kubectl apply -f dashboard/kubernetes-dashboard.yaml
  kubectl apply -f dashboard/admin-user-service-account.yaml
  kubectl apply -f dashboard/admin-user-secret.yaml
  waitFor kubernetes-dashboard
}

adminDashboard
