#!/usr/bin/env bash

createStandard() {
  kubectl create namespace standard
  createTlsSecret standard
  kubectl -n standard apply -f backend/standard/redis && waitFor redis
  kubectl -n standard apply -f backend/standard/mongo && waitFor mongo

  {
    # Nodejs
    kubectl -n standard apply -f backend/standard/todo && waitFor todo
    kubectl -n standard apply -f backend/standard/sshwifty && waitFor sshwifty
    kubectl -n standard apply -f backend/standard/zipcode && waitFor zipcode
    kubectl -n standard apply -f backend/standard/mongo-blog && waitFor mongo-blog
    kubectl -n standard apply -f backend/standard/simple-chat && waitFor simple-chat
  } &
  {
    # Nginx
    kubectl -n standard apply -f backend/standard/tetris && waitFor tetris
    kubectl -n standard apply -f backend/standard/anywaychat && waitFor anywaychat
    kubectl -n standard apply -f backend/standard/ramen-timer && waitFor ramen-timer

    # PHP
    kubectl -n standard apply -f backend/standard/dokuwiki && waitFor dokuwiki
    kubectl -n standard apply -f backend/standard/shop && waitFor shop

    # Python
    kubectl -n standard apply -f backend/standard/tutorial && waitFor tutorial
    # kubectl -n standard apply -f backend/standard/fastapi && waitFor fastapi
    # kubectl -n standard apply -f backend/standard/django && waitFor django

    # Other
    kubectl -n standard apply -f backend/standard/whoami && waitFor whoami
  } &

  wait

  kubectl -n standard describe nodes
  # kubectl config set-context $(kubectl config current-context) --namespace default
}

createStandard
