apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
spec:
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
      - name: bind9
        image: jobscale/bind9
        imagePullPolicy: Always
