apiVersion: v1
kind: Service
metadata:
  name: bind9
  labels:
    app: bind9
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    nodePort: 30053
    port: 53
    targetPort: 53
  - name: udp
    nodePort: 30053
    port: 53
    targetPort: 53
    protocol: UDP
  selector:
    app: bind9
