apiVersion: v1
kind: Service
metadata:
  name: bind9
spec:
  selector:
    app: bind9
  type: LoadBalancer
  ports:
  - name: udp
    nodePort: 30053
    port: 53
    targetPort: 53
    protocol: UDP
  # - name: tcp
  #   nodePort: 30053
  #   port: 53
  #   targetPort: 53
  #   protocol: TCP
