apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-chat
  labels:
    app: simple-chat
    component: deployment
spec:
  selector:
    matchLabels:
      app: simple-chat
  template:
    metadata:
      labels:
        app: simple-chat
        component: workload
    spec:
      containers:
      - image: ghcr.io/jobscale/simple-chat
        name: simple-chat
---
apiVersion: v1
kind: Service
metadata:
  name: simple-chat
  labels:
    app: simple-chat
    component: service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: simple-chat
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-chat
  labels:
    app: simple-chat
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-chat
  maxReplicas: 3
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-chat
  labels:
    name: simple-chat
    component: ingress
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: [ "simple-chat.jsx.jp" ]
  rules:
  - host: simple-chat.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: simple-chat
            port:
              number: 80
