#!/usr/bin/env bash

network() {
  [[ $(docker network list | grep standard | wc -l) == 0 ]] && docker network create standard
}

logrotate() {
  docker pull blacklabelops/logrotate
  docker rm -f logrotate
  docker run --name logrotate --restart always \
  --memory 64m \
  -v /var/lib/docker/containers:/var/lib/docker/containers \
  -v /var/log/daemon:/var/log/daemon \
  -e "LOGS_DIRECTORIES=/var/lib/docker/containers /var/log/daemon" \
  -e "LOGROTATE_INTERVAL=daily" \
  -e "LOGROTATE_COPIES=90" \
  -d blacklabelops/logrotate
}

lo-stack() {
  # docker pull localstack/localstack
  docker pull ghcr.io/jobscale/localstack
  docker rm -f lo-stack
  docker run --name lo-stack --restart always \
  --memory 800m \
  -e PERSISTENCE=1 \
  -v $HOME/lo-stack-volume:/var/lib/localstack \
  -p 4566:4566 \
  -d ghcr.io/jobscale/localstack
}

proxy-nodejs() {
  docker pull ghcr.io/jobscale/proxy-nodejs
  docker rm -f proxy-nodejs
  docker run --name proxy-nodejs --restart always \
  --memory 120m \
  -p 3128:3128 \
  -d ghcr.io/jobscale/proxy-nodejs
}

squid-secure() {
  docker pull ghcr.io/jobscale/squid:secure
  docker rm -f squid
  docker run --name squid --restart always \
  --memory 320m \
  -p 3128:3128 \
  -d ghcr.io/jobscale/squid:secure
}

squid() {
  docker pull ghcr.io/jobscale/squid:main
  docker rm -f squid
  docker run --name squid --restart always \
  --memory 320m \
  -p 3128:3128 \
  -d ghcr.io/jobscale/squid:main
}

dns-nodejs() {
  docker pull ghcr.io/jobscale/dns-nodejs
  docker rm -f bind9 # Alt
  docker rm -f dns-nodejs
  docker run --name dns-nodejs --restart always \
  --memory 128m \
  --shm-size 128m \
  -p 53:53 -p 53:53/udp \
  -d ghcr.io/jobscale/dns-nodejs
}

bind9() {
  docker pull ghcr.io/jobscale/bind9
  docker rm -f dns-nodejs # Alt
  docker rm -f bind9
  docker run --name bind9 --restart always \
  --memory 54m \
  -p 53:53 -p 53:53/udp \
  -d ghcr.io/jobscale/bind9
}

partner() {
  docker pull ghcr.io/jobscale/partner
  docker rm -f partner.credentials.svc.cluster.local
  docker run --name partner.credentials.svc.cluster.local --restart always \
  --network standard -d ghcr.io/jobscale/partner
}

jsxjp() {
  docker pull ghcr.io/jobscale/jsxjp
  docker rm -f jsxjp.jsxjp.svc.cluster.local
  docker run --name jsxjp.jsxjp.svc.cluster.local --restart always \
  --network standard -d ghcr.io/jobscale/jsxjp
}

tanpo() {
  docker pull ghcr.io/jobscale/tanpo
  docker rm -f tanpo.standard.svc.cluster.local
  docker run --name tanpo.standard.svc.cluster.local --restart always \
  --network standard -d ghcr.io/jobscale/tanpo
}

web() {
  docker pull ghcr.io/jobscale/web
  docker rm -f web
  docker run --name web --restart always \
  --network standard \
  -p 80:80 -p 443:443 \
  -d ghcr.io/jobscale/web
}

wetty() {
  sudo mkdir -p /var/lib/wetty
  docker pull ghcr.io/jobscale/wetty:dind
  docker rm -f wetty.standard.svc.cluster.local
  docker run --name wetty.standard.svc.cluster.local --restart always \
  --network standard --privileged -v /var/lib/wetty:/var/lib/docker \
  -d ghcr.io/jobscale/wetty:dind
}

webtop() {
  docker pull ghcr.io/jobscale/docker-webtop:xfce
  docker rm -f webtop
  docker run --name webtop --restart always \
  --privileged \
  --memory 8g \
  --shm-size 8g \
  -e PUID=1000 \
  -e PGID=50 \
  -e TZ=Europe/Paris \
  -e CUSTOM_PORT=2999 \
  -e CUSTOM_USER=jobscale \
  -e USERNAME=jobscale \
  -e USER=jobscale \
  -p 2999:2999 \
  -p 2997:8000 \
  -v /home/webtop/debian:/config \
  -d ghcr.io/jobscale/docker-webtop:xfce

  # lscr.io/linuxserver/webtop:debian-xfce
}

llm-gemma-3() {
  # docker pull ghcr.io/jobscale/llama.cpp:gemma-3-4B-Q3
  docker rm -f llm.gemma-3
  docker run --name llm.gemma-3 \
  --memory 8g \
  --shm-size 8g \
  -p 2880:8080 \
  -d ghcr.io/jobscale/llama.cpp:gemma-3-4B-Q3
}

ls-logs() {
  LIST=($(sudo ls /var/lib/docker/containers))
  for i in ${LIST[@]}
  do
    sudo jq .Name /var/lib/docker/containers/$i/config.v2.json
    sudo ls -ltr /var/lib/docker/containers/$i
  done
}

inet() {
  docker ps
  iInfo() {
    echo -en "$(date --rfc-3339=seconds) - "
    https_proxy=127.0.0.1:3128 curl -s https://inet-ip.info/ip
  }
  echo $(iInfo)
  for i in {1..3}
  do
    sleep 2.97
    echo $(iInfo)
  done
}

proxies() {
  connect() {
    https_proxy=proxy.$1.jsx.jp:3128 curl -s https://inet-ip.info/ip
  }
  time connect secure
  time connect os
  time connect eu
  time connect us
}

{
  THIS=${0##*/}
  grep ^[a-z] containers | awk -F'(' '{print $1}'
}
