#!/usr/bin/env bash
set -u

LIST=(
  ec-cube
  php-fpm
  mongo-blog
  webssh
  python-fastapi
  partner
  ramen-timer
  node-express-ejs-authorization
  wetty
  value-domain
  jsxjp
  web
  todo
  bind9
  nginx-net
  nginx-tls
  tetris
  django
  bastion
  certbot
  squid
  wordpress
  focal
  node-aws
  cloud-terminal
  health-check
  speedtest-slack
  eslint
  certificate
  gitlab
  svn
  dokuwiki
  anywaychat
  room-chat
  mqtt-chat
  swagger-editor
  wallgame
  autocannon
  basic-auth
  profile
  mp4box
  webm
  simple-chat
  lumen
  laravel
)

{
  for i in ${LIST[@]}
  do
    docker pull ghcr.io/jobscale/$i && docker tab ghcr.io/jobscale/$i jobscale/$i && docker push jobscale/$i
  done
} 2>&1
