#!/usr/bin/env bash
set -eu

LIST=(
  php-fpm
  php-fpm:xdebug
  node-aws
  node-aws:dind
  mongo-blog
  webssh
  python-fastapi
  partner
  ramen-timer
  node-express-ejs-authorization
  wetty
  value-domain
  jsxjp
  web
  bind9
  nginx-net
  nginx-tls
  tetris
  django
  bastion
  certbot
  squid
  cloud-terminal
  health-check
  speedtest-slack
  eslint
  certificate
  gitlab
  svn
  dokuwiki
  anywaychat
  room-chat
  mqtt-chat
  swagger-editor
  wallgame
  autocannon
  basic-auth
  profile
  mp4box
  webm
  simple-chat
  lumen
  laravel
  todo
  todo:nginx
  ec-cube
)

loop() {
  for i in ${LIST[@]}
  do
    ./docker-manifest $i
  done
}

main() {
  echo "START $(date)"
  time loop 2>&1 || date
  echo "FINISH $(date)"
}

{
  LOG_FILE=$HOME/docker-list-$(date +%s).log
  main | tee -a $LOG_FILE
  grep -i -1 error $LOG_FILE
  grep -i -1 fail $LOG_FILE
  grep -i -1 invalid $LOG_FILE
  grep -i -1 unknown $LOG_FILE
}
