apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: default
data:
  docker.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
    default_authentication_plugin=mysql_native_password
    sql-mode=
