kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  namespace: mysql
spec:
  storageClassName: mysql
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/var/lib/mysql"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim
  namespace: mysql
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
