apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp
spec:
  selector:
    matchLabels:
      app: exp
  template:
    metadata:
      labels:
        app: exp
    spec:
      containers:
      - image: ghcr.io/jobscale/node-express-ejs-authorization
        name: exp
---
apiVersion: v1
kind: Service
metadata:
  name: exp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: exp
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: exp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exp
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exp
  labels:
    name: exp
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: ["exp.jsx.jp"]
  rules:
  - host: exp.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: exp
            port:
              number: 80
