#!/usr/bin/env bash

cleanZombie() {
  PID=$(ps auxf | grep "ssh [n]oble-watch" | awk '{print $2}')
  [[ "$PID" == "" ]] || {
    kill $PID
    echo "$(TZ=Asia/Tokyo date -Iseconds) process killing $PID" 1>&2
  }
}

whileCheck() {
  cleanZombie
  while true
  do
    sleep 60
    nc -vz -w 1 vpn.jsx.jp 2022 > /dev/null 2>&1
    [[ $(echo $?) == 0 ]] || cleanZombie && continue
  done
}

{
  whileCheck &
  while true
  do
    REMOTE=$(dig vpn.jsx.jp | grep -1 "ANSWER SECTION" | tail -1 | awk '{print $5}')
    PRINT="backdoor-os - ${REMOTE} from $(hostname) in $(TZ=Asia/Tokyo date -Iseconds)"
    echo "$PRINT"
    CHANNEL=secure timeout 10 /home/jobscale/bin/post-slack "$PRINT"
    sudo -u jobscale ssh-keygen -f "/home/jobscale/.ssh/known_hosts" -R "vpn.jsx.jp"
    sudo -u jobscale ssh -N -T noble-watch
    sleep 60
  done
}
