#!/usr/bin/env bash
set -eu

linkDot() {
  for i in .[a-z]*
  do
    echo $i
    rm -f ~/$i
    ln -fns $(pwd)/$i ~
  done
}

cloneVim() {
  [ -s "$HOME/.vim/bundle/Vundle.vim" ] && return
  git clone --depth 1 https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
  vim +PluginInstall +qall
}

main () {
  [[ $(pwd) == "$HOME" ]] && echo "can't be symbolic link" && return
  linkDot
  cloneVim
}

main
