apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-server-pv
spec:
  storageClassName: ssd.sda
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/extra/home/store"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code-server-pv-claim
spec:
  storageClassName: ssd.sda
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
        component: workload
    spec:
      volumes:
      - name: code-server-persistent-storage
        persistentVolumeClaim:
          claimName: code-server-pv-claim
      containers:
      - image: ghcr.io/jobscale/code-server
        name: code-server
        volumeMounts:
        - name: code-server-persistent-storage
          mountPath: /home/store
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  labels:
    app: code-server
    component: service
spec:
  selector:
    app: code-server
  type: LoadBalancer
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: code-server
  labels:
    app: code-server
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: code-server
  maxReplicas: 3
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: code-server
  labels:
    app: code-server
    component: middleware
spec:
  basicAuth:
    secret: basic-auth
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: code-server
  labels:
    app: code-server
    component: ingress
spec:
  entryPoints: [ web, websecure ]
  tls:
    secretName: jsxjp-tls
  routes:
  - match: Host("code-server.jsx.jp")
    kind: Rule
    middlewares:
    - name: code-server
    services:
    - name: code-server
      port: 80
  - match: Host("code-server.x.jsx.jp")
    kind: Rule
    middlewares:
    - name: code-server
    services:
    - name: code-server
      port: 80
