apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - name: web
        image: jobscale/web:0.0.5
        ports:
        - containerPort: 443
          protocol: TCP
        - containerPort: 80
          protocol: TCP
