apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - name: web
        image: jobscale/web:0.0.6
        resources:
          limits:
            cpu: 200m
            memory: 500M
          requests:
            cpu: 120m
            memory: 300M
