apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    run: web
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: web
