apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
  - name: https
    nodePort: 30443
    port: 443
    targetPort: 443
    protocol: TCP
  - name: http
    nodePort: 30080
    port: 80
    targetPort: 80
    protocol: TCP
