#!/usr/bin/env bash

ddns() {
  docker pull ghcr.io/jobscale/sakura-dns
  docker run --rm -e ENV=${ENV:-dev} \
  -e DOMAIN=$1 \
  -e TOKEN=$(date +%s) \
  -e DNS_CONFIG=$(cat /root/_/infra/dns-config) \
  -t ghcr.io/jobscale/sakura-dns
}

ddns-dev() {
  ddns os
}

ddns-prod() {
  ddns us
}

type-a-proxy() {
  docker run --rm -e ENV=${ENV:-dev} \
  -e DOMAIN=proxy \
  -e TYPE=A \
  -e R_DATA=172.16.6.66 \
  -e TOKEN=$(date +%s) \
  -e DNS_CONFIG=$(cat /root/_/infra/dns-config) \
  -t ghcr.io/jobscale/sakura-dns
}

update-infra() {
  cd /root/_ && git pull
  cd /home/jobscale/_ && sudo -u jobscale git pull
  curl -sL jsx.jp/s/ed25519.pem.pub | tee -a /home/jobscale/.ssh/authorized_keys
  cat /home/jobscale/.ssh/authorized_keys | tee -a /root/.ssh/authorized_keys
  echo 'GatewayPorts yes' | tee -a /etc/ssh/sshd_config
  hostname "$ENV"
  echo "$ENV" | tee /etc/hostname
}

time {
  MESSAGE="AutoScaling EC2 - ${ENV} $(TZ=Asia/Tokyo date -Iseconds)"
  echo "${MESSAGE}"
  which docker || curl -sL jsx.jp/s/user-data | bash
  update-infra
  ddns-${ENV}
  CHANNEL=infra /root/_/bin/post-slack "${MESSAGE}" &
}
