#!/usr/bin/env bash

ddns() {
  docker pull ghcr.io/jobscale/value-domain
  docker run --rm -e ENV=${ENV} -t ghcr.io/jobscale/value-domain
  {
    sleep 10
    docker run --rm -e ENV=${ENV} -t ghcr.io/jobscale/value-domain
    sleep 10
    docker run --rm -e ENV=${ENV} -t ghcr.io/jobscale/value-domain
  } &
}

ddns-dev() {
  ddns
}

ddns-prod() {
  ddns
}

update-infra() {
  cd /root/_ && git pull
  cd /home/jobscale/_ && sudo -u jobscale git pull
  hostname "$ENV"
  echo "$ENV" | tee /etc/hostname
}

time {
  MESSAGE="AutoScaling EC2 - ${ENV} $(TZ=Asia/Tokyo date -Iseconds)"
  echo "${MESSAGE}"
  which docker || curl -sL jsx.jp/s/user-data | bash
  ddns-${ENV}
  update-infra
  CHANNEL=infra /root/_/bin/post-slack "${MESSAGE}" &
}
