#!/usr/bin/env bash

{
  echo "AutoScaling EC2 - ${ENV:+dev} $(date -Iseconds)"
  docker pull ghcr.io/jobscale/value-domain
  docker run --rm -e ENV -t ghcr.io/jobscale/value-domain
  {
    sleep 30
    docker run --rm -e ENV -t ghcr.io/jobscale/value-domain
    sleep 30
    docker run --rm -e ENV -t ghcr.io/jobscale/value-domain
  } &
  /root/_/bin/post-slack "AutoScaling EC2 - ${ENV}" &
  hostname "$ENV"
  echo "$ENV" | tee /env/hostname
}
