#!/usr/bin/env bash

ddns() {
  docker pull ghcr.io/jobscale/value-domain
  docker run --rm -e ENV=${ENV} -t ghcr.io/jobscale/value-domain
  {
    sleep 30
    docker run --rm -e ENV=${ENV} -t ghcr.io/jobscale/value-domain
    sleep 30
    docker run --rm -e ENV=${ENV} -t ghcr.io/jobscale/value-domain
  } &
}

ddns-dev() {
  /usr/local/bin/noip2
  ddns
}

ddns-prod() {
  ddns
}

update-infra() {
  cd /root/_ && git pull
  cd /home/jobscale/_ && sudo -u jobscale git pull
}

{
  MESSAGE="AutoScaling EC2 - ${ENV:+dev} $(date -Iseconds)"
  echo "${MESSAGE}"
  update-infra
  CHANNEL=infra /root/_/bin/post-slack "${MESSAGE}" &
  hostname "$ENV"
  echo "$ENV" | tee /etc/hostname
  ddns-${ENV}
}
