#!/usr/bin/env bash
set -eu

export DEBIAN_FRONTEND=noninteractive

{
  curl -sL -o "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-$(arch).zip"
  unzip awscliv2.zip
  sudo ./aws/install
  rm -fr aws awscliv2.zip
}
