#!/usr/bin/env bash
set -eu

certonly() {
  apt update && apt install -y certbot
  certbot certonly --rsa-key-size 4096 --no-bootstrap --manual --manual-public-ip-logging-ok -d jsx.jp -d *.jsx.jp -d *.in.jsx.jp --preferred-challenges dns --agree-tos --register-unsafely-without-email
  cd /etc/letsencrypt/live
  rm $(find . -name README)
  zip -r /etc/nginx/tls *
}

testing() {
  docker network create standard
  docker pull jobscale/partner
  docker run --rm --name partner --network standard -d jobscale/partner
  docker pull jobscale/web
  docker run --rm --name web --network standard -it jobscale/web
  docker stop partner
  docker network rm standard
}
