#!/usr/bin/env bash -eu

install() {
  curl -Ls -o /usr/local/bin/certbot-auto https://raw.githubusercontent.com/certbot/certbot/master/certbot-auto
  chmod +x /usr/local/bin/certbot-auto
  certbot-auto --os-packages-only --non-interactive
  certbot-auto --no-bootstrap --version
}

certonly() {
  certbot-auto --no-bootstrap certonly --manual --manual-public-ip-logging-ok -d jsx.jp -d *.jsx.jp -d *.in.jsx.jp --preferred-challenges dns --agree-tos --register-unsafely-without-email
  cd /etc/letsencrypt/live
  rm $(find . -name README)
  zip -r /etc/nginx/tls *
}

testing() {
  docker network create standard
  docker pull jobscale/partner
  docker run --rm --name partner --network standard -d jobscale/partner
  docker pull jobscale/web
  docker run --rm --name web --network standard -it jobscale/web
  docker stop partner
  docker network rm standard
}

