#!/usr/bin/env bash
set -eu

{
  curl -sLO "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  sudo apt install -y ./google-chrome-stable_current_amd64.deb
  rm google-chrome-stable_current_amd64.deb
}
