#!/usr/bin/env bash
set -eu

{
  cd /tmp
  sudo apt-get update
  curl -LO "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
  rm google-chrome-stable_current_amd64.deb
  cd -
}
