#!/usr/bin/env bash
set -eu

iCinnamon() {
  sudo apt-get update && sudo apt-get install -y --no-install-recommends \
  cinnamon-desktop-environment
  apt-cache search cinnamon | grep ^cinnamon | sort
}

iCinnamon
