#!/usr/bin/env bash
set -eux

export DEBIAN_FRONTEND=noninteractive

iNodejs() {
  curl -o- https://raw.githubusercontent.com/creationix/nvm/$(
    git ls-remote --tags --refs https://github.com/nvm-sh/nvm.git | grep -P 'v0.\d\d' | tail -1 | awk -F/ '{print $3}'
  )/install.sh | bash
  echo $SHELL | grep bash && source ~/.bashrc
  echo $SHELL | grep zsh && source ~/.zshrc
  LATEST=$(nvm ls-remote | grep 'Latest LTS' | tail -1 | awk '{print $1}')
  nvm install $LATEST
  nvm alias default $LATEST
  nvm use $LATEST
  npm version | xargs
  node --version
  npm --version
  id
}

iAws() {
  curl -sL -o awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  unzip awscliv2.zip
  sudo ./aws/install
  rm -fr aws awscliv2.zip
  sudo pip3 install awslogs
  curl -sL "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
  sudo mv /tmp/eksctl /usr/local/bin
  aws --version
}

iServerless() {
  npm i -g serverless
  serverless --version
}

iSam() {
  pip install aws-sam-cli --user
  sam --version
}

iAmplify() {
  npm i -g @aws-amplify/cli
  amplify --version
}

iVue() {
  npm i -g @vue/cli
  vue --version
}

main() {
  cd $HOME
  iNodejs
  iAws
  iServerless
  iSam
  iAmplify
  iVue
}

{
  date +'BEGIN $0 develop %Y-%m-%d %H:%M:%S'
  which lsb_release && lsb_release -cs || echo "no lsb_release"
  eval $(cat /etc/*release)
  main
  date +'END   $0 develop %Y-%m-%d %H:%M:%S'
}
