#!/usr/bin/env bash
set -eu

export DEBIAN_FRONTEND=noninteractive

debian() {
  apt-get update
  apt-get install -y apt-transport-https
  apt-get update
  sudo apt-get install -y software-properties-common ca-certificates gnupg

  id=$(lsb_release -is)
  echo ${id,,} $(lsb_release -cs)
  curl -fsSL https://download.docker.com/linux/${id,,}/gpg | apt-key add -
  add-apt-repository "deb https://download.docker.com/linux/${id,,} $(lsb_release -cs) stable"
  apt install -y docker-ce docker-ce-cli containerd.io
  echo -- sudo usermod -aG docker \$\(whoami\)
}

ubuntu() {
  apt update
  apt install -y apt-transport-https

  id=$(lsb_release -is)
  echo ${id,,} $(lsb_release -cs)
  curl -fsSL https://download.docker.com/linux/${id,,}/gpg | apt-key add -
  add-apt-repository "deb https://download.docker.com/linux/${id,,} $(lsb_release -cs) stable"
  apt install -y docker-ce
  echo -- sudo usermod -aG docker \$\(whoami\)
}

# Debian 10
buster() {
  debian
}

# Debian 11
bullseye() {
  debian
}

# Ubuntu 20.04
focal() {
  ubuntu
}

# Ubuntu 22.04
jammy() {
  ubuntu
}

{
  date +'BEGIN $0 docker %Y-%m-%d %H:%M:%S'
  which lsb_release && lsb_release -cs
  eval $(cat /etc/*release)
  $VERSION_CODENAME
  date +'END   $0 docker %Y-%m-%d %H:%M:%S'
}
