#!/bin/bash -eu

# Debian 10
buster() {
  apt-get update
  apt-get install -y apt-transport-https
  apt-get update
  apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

  apt-get update
  apt-get -y install docker-ce docker-ce-cli containerd.io
  echo -- usermod -aG docker \$\(whoami\)
}

# Debian 11
bullseye() {
  apt-get update
  apt-get install -y apt-transport-https
  apt-get update
  apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

  apt-get update
  apt-get -y install docker-ce docker-ce-cli containerd.io
  echo -- usermod -aG docker \$\(whoami\)
}

# Ubuntu 20.04
focal() {
  apt update
  apt install -y apt-transport-https
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  apt install -y docker-ce
  echo -- usermod -aG docker \$\(whoami\)
}

{
  which lsb_release && lsb_release -cs
  eval $(cat /etc/*release)
  $VERSION_CODENAME
}
