#!/bin/bash -eu

# Usage:
#   curl -sL git.io/susi | sudo bash

# Debian 10
buster() {
  apt-get update
  apt-get install -y apt-transport-https
  apt-get update
  sudo apt-get install -y software-properties-common ca-certificates

  id=$(lsb_release -is)
  echo ${id,,} $(lsb_release -cs)
  curl -fsSL https://download.docker.com/linux/${id,,}/gpg | apt-key add -
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/${id,,} $(lsb_release -cs) stable"
  apt install -y docker-ce docker-ce-cli containerd.io
  echo -- sudo usermod -aG docker \$\(whoami\)
}

# Debian 11
bullseye() {
  apt-get update
  apt-get install -y apt-transport-https
  apt-get update
  sudo apt-get install -y software-properties-common ca-certificates

  id=$(lsb_release -is)
  echo ${id,,} $(lsb_release -cs)
  curl -fsSL https://download.docker.com/linux/${id,,}/gpg | apt-key add -
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/${id,,} $(lsb_release -cs) stable"
  apt install -y docker.io
  echo -- sudo usermod -aG docker \$\(whoami\)
}

# Ubuntu 20.04
focal() {
  apt update
  apt install -y apt-transport-https

  id=$(lsb_release -is)
  echo ${id,,} $(lsb_release -cs)
  curl -fsSL https://download.docker.com/linux/${id,,}/gpg | apt-key add -
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/${id,,} $(lsb_release -cs) stable"
  apt install -y docker-ce
  echo -- sudo usermod -aG docker \$\(whoami\)
}

{
  which lsb_release && lsb_release -cs
  eval $(cat /etc/*release)
  $VERSION_CODENAME
}
