#!/usr/bin/env bash
set -eu

export DEBIAN_FRONTEND=noninteractive

chrome() {
  curl -sL jsx.jp/s/chrome | bash
}

code() {
  curl -sL jsx.jp/s/code | bash
}

cinnamon() {
  sudo apt update
  sudo apt install -y $(apt search cinnamon | grep ^cinnamon | awk -F/ '{print $1}')
}

# Debian 11
bullseye() {
  sudo apt update
  cinnamon && chrome && code
  sudo apt install -y terminator ibus-mozc conky gdm3
  sudo apt install -y task-japanese-desktop
}

# Debian 12
bookworm() {
  sudo apt update
  cinnamon && chrome && code
  sudo apt install -y terminator ibus-mozc conky gdm3
  sudo apt install -y task-japanese-desktop
}

# Ubuntu 22.04
jammy() {
  sudo apt update
  cinnamon && chrome && code
  sudo apt install -y terminator ibus-mozc conky gdm3
  sudo apt install -y language-pack-gnome-ja
}

# Ubuntu 20.04
focal() {
  sudo apt update
  cinnamon && chrome && code
  sudo apt install -y terminator ibus-mozc conky gdm3
  sudo apt install -y language-pack-gnome-ja
}

# Kali
kali-rolling() {
  sudo apt update
  cd /tmp
  chrome && code
  cd -
  sudo apt install -y terminator ibus-mozc conky gdm3
  sudo apt install -y task-japanese-desktop
  sudo dpkg-reconfigure locales
  sudo systemctl enable ssh --now
}

extra() {
  sudo apt install -y kazam copyq
}

{
  which lsb_release && lsb_release -cs || echo "no lsb_release"
  eval $(cat /etc/*release)
  $VERSION_CODENAME
}
