#!/usr/bin/env bash
set -eu

export DEBIAN_FRONTEND=noninteractive

symbolic-links() {
  mv ダウンロード Downloads && ln -s Downloads ダウンロード
  mv テンプレート Templates && ln -s Templates テンプレート
  mv デスクトップ Desktop && ln -s Desktop デスクトップ
  mv ドキュメント Documents && ln -s Documents ドキュメント
  mv ビデオ Videos && ln -s Videos ビデオ
  mv 音楽 Music && ln -s Music 音楽
  mv 画像 Pictures && ln -s Pictures 画像
  mv 公開 Public && ln -s Public 公開
}

debian-2022() {
  sudo apt update
  sudo apt install -y --no-install-recommends \
    terminator ibus-mozc conky gdm3 ffmpeg libsecret-tools
  sudo apt install \
    task-japanese-desktop
}

debian-2025() {
  sudo apt update
  sudo apt install -y --no-install-recommends \
    terminator ibus-mozc conky-all gdm3 ffmpeg libsecret-tools
  sudo apt install \
    task-japanese-desktop
  sudo dpkg-reconfigure gdm3
}

ubuntu() {
  sudo apt update
  sudo apt install -y --no-install-recommends \
    terminator ibus-mozc conky gdm3 ffmpeg libsecret-tools
  sudo apt install \
    language-pack-gnome-ja
}

kali-rolling() {
  sudo apt update
  sudo apt install -y --no-install-recommends \
    terminator ibus-mozc conky gdm3 ffmpeg libsecret-tools
  sudo apt install \
    task-japanese-desktop
  sudo dpkg-reconfigure locales
  sudo systemctl enable ssh --now
}

extra() {
  sudo apt install -y --no-install-recommends \
    kazam copyq
}

main() {
  echo "$(lsb_release -a 2>/dev/null || echo "$(date --rfc-3339=seconds) [WARN] No LSB modules are available.")"
  . /etc/os-release

  start() {
    echo "$(date --rfc-3339=seconds) [INFO] START  graphical for $VERSION_CODENAME"
  }
  finish() {
    echo "$(date --rfc-3339=seconds) [INFO] FINISH graphical for $VERSION_CODENAME"
  }
  trap 'finish' EXIT
  start

  case "$VERSION_CODENAME" in
    trixie)
      debian-2025
      ;;
    bookworm|bullseye|buster)
      debian-2022
      ;;
    noble|jammy|focal)
      ubuntu
      ;;
    kali-rolling)
      kali-rolling
      ;;
    *)
      echo "$(date --rfc-3339=seconds) [FAIL] Unsupported distribution: $VERSION_CODENAME"
      exit 1
      ;;
  esac
}

main "$@"
