#!/usr/bin/env bash
set -eu

export DEBIAN_FRONTEND=noninteractive

jaJP() {
  apt update
  apt install -y locales

  sed -i -e 's/# ja_JP.UTF-8 UTF-8/ja_JP.UTF-8 UTF-8/' /etc/locale.gen
  locale-gen
  update-locale LANG=ja_JP.UTF-8
  echo "export TZ=Asia/Tokyo" | tee -a /etc/bash.bashrc
}

{
  echo "BEGIN ja-jp $(date --rfc-3339=seconds)"
  jaJP
  echo "END   ja-jp $(date --rfc-3339=seconds)"
}
