#!/usr/bin/env bash
set -eu

{
  curl -sL jsx.jp/s/auth-gen | bash
  curl -sLO jsx.jp/s/guest-ed255.pem
  chmod 600 guest-ed255.pem
  ssh -tt -o 'StrictHostKeyChecking=no' -o 'RemoteCommand=watch date --rfc-3339=seconds' -i guest-ed255.pem -R 3022:bastion.a.jsx.jp:22 guest@bastion.us.jsx.jp
}
