#!/usr/bin/env bash

##
## with Linux
##

eval $(cat /etc/*release)

web() {
  sudo apt install -y $(apt search php | grep "^php7" | grep -v snmp | awk -F'/' '{print $1}' | xargs) nginx nginx-extras
  rm -f /etc/nginx/sites-enabled/default
  cp -pr /var/site/projects/_/conf.d /etc/nginx
  ln -sfn /run/php/php7*sock /var/site/run/php/php-fpm.sock
  chown -R www-data. /var/log/nginx
  systemctl restart nginx
}

cli() {
  export DEBIAN_FRONTEND=noninteractive
  sudo apt update
  sudo apt install -y \
    curl dnsutils iproute2 iputils-ping whois nmap traceroute \
    git subversion vim tmux dstat procps peco \
    at expect zip unzip colordiff speedtest-cli \
    cmatrix sl \
    nfs-common cifs-utils exfat-utils sshfs ecryptfs-utils
}

gui() {
  export DEBIAN_FRONTEND=noninteractive
  sudo apt update
  sudo apt install -y git vim curl iproute2 dnsutils procps tmux sl cmatrix netcat locate openssh-server terminator conky ibus-mozc \
    $(apt search cinnamon | grep ^cinnamon | awk -F/ '{print $1}')
  sudo sed -i -e 's/# ja_JP.UTF-8 UTF-8/ja_JP.UTF-8 UTF-8/' /etc/locale.gen && sudo locale-gen && sudo update-locale LANG=ja_JP.UTF-8
  # gsettings set org.freedesktop.ibus.panel xkb-icon-rgba '#f57900'
}

iAws() {
  curl -sL -o awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  unzip awscliv2.zip
  sudo ./aws/install
  rm -fr aws awscliv2.zip
  sudo pip3 install awslogs
  curl -sL "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
  sudo mv /tmp/eksctl /usr/local/bin
}

iAz() {
  python3 -m pip install --user azure-cli
}

iGcloud() {
  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  sudo add-apt-repository "deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -cs) main"
  sudo apt install -y google-cloud-sdk
}

useFunction() {
  user=$(grep -w 1000 /etc/passwd | awk -F: '{print $1}')
  name=$1
  command="$@"
  type $name | tail -$(echo $(type $name | wc -l)-1 | bc) > /tmp/$name
  sudo -u $user bash -c ". /tmp/$name && $command"
  rm /tmp/$name
}

account() {
  user=jobscale
  old=$(grep -w 1000 /etc/passwd | awk -F: '{print $1}')
  sudo usermod -l $user -m -d /home/$user $old
  echo "$user ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/70-users
  sudo systemctl restart sshd
}

system() {
  sudo dd if=/dev/zero of=/swapfile bs=20M count=120 status=progress
  sudo chmod 0600 /swapfile
  sudo mkswap /swapfile
  sudo swapon /swapfile
  echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
  sudo mount -a
}

minimum() {
  export DEBIAN_FRONTEND=noninteractive
  apt update && apt install -y --no-install-recommends \
    git vim tmux curl zip unzip iproute2 dnsutils procps iputils-ping
}

db() {
  apt install -y --no-install-recommends mariadb-server
}

cli() {
  apt install -y --no-install-recommends \
    curl whois nmap traceroute iproute2 \
    nfs-common cifs-utils exfat-utils sshfs \
    git subversion vim tmux dstat peco \
    at expect zip unzip colordiff speedtest-cli \
    mariadb-client libpng-dev nasm
}

account() {
  user=$(grep -w 1000 /etc/passwd | awk -F: '{print $1}')
  echo "$user ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers.d/70-users
}

main() {
  date +'START    my-init %Y-%m-%d %H:%M:%S'
  [[ $(id -u) == 0 ]] && alias sudo=''
  echo installing...
  date +'FINISHED my-init %Y-%m-%d %H:%M:%S'
}
