#!/usr/bin/env bash

##
## with Linux
##

eval $(cat /etc/*release)

web() {
  sudo apt install -y $(apt search php | grep "^php7" | grep -v snmp | awk -F'/' '{print $1}' | xargs) nginx nginx-extras
  rm -f /etc/nginx/sites-enabled/default
  cp -pr /var/site/projects/_/conf.d /etc/nginx
  ln -sfn /run/php/php7*sock /var/site/run/php/php-fpm.sock
  chown -R www-data. /var/log/nginx
  systemctl restart nginx
}

cli() {
  export DEBIAN_FRONTEND=noninteractive
  sudo apt update
  sudo apt install -y \
    curl dnsutils iproute2 iputils-ping whois nmap traceroute \
    git subversion vim tmux dstat procps peco \
    at expect zip unzip colordiff speedtest-cli \
    cmatrix sl \
    nfs-common cifs-utils exfat-utils sshfs ecryptfs-utils
}

gui() {
  export DEBIAN_FRONTEND=noninteractive
  sudo apt update
  sudo apt install -y git vim curl iproute2 dnsutils procps tmux sl cmatrix netcat locate openssh-server terminator conky ibus-mozc \
    $(apt search cinnamon | grep ^cinnamon | awk -F/ '{print $1}')
  sudo sed -i -e 's/# ja_JP.UTF-8 UTF-8/ja_JP.UTF-8 UTF-8/' /etc/locale.gen && sudo locale-gen && sudo update-locale LANG=ja_JP.UTF-8
  # gsettings set org.freedesktop.ibus.panel xkb-icon-rgba '#f57900'
}

iNodejs() {
  curl -o- https://raw.githubusercontent.com/creationix/nvm/$(
    git ls-remote --tags --refs https://github.com/nvm-sh/nvm.git | grep -P 'v0.\d\d' | tail -1 | awk -F/ '{print $3}'
  )/install.sh | bash
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  LATEST=$(nvm ls-remote | grep 'Latest LTS' | tail -1 | awk '{print $1}')
  nvm install $LATEST
  nvm alias default $LATEST
  nvm use $LATEST
  node --version
  npm --version
  id
}

iAws() {
  curl -sL -o awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  unzip awscliv2.zip
  sudo ./aws/install
  rm -fr aws awscliv2.zip
  sudo pip3 install awslogs
  curl -sL "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
  sudo mv /tmp/eksctl /usr/local/bin
}

iAz() {
  python3 -m pip install --user azure-cli
}

iGcloud() {
  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  sudo add-apt-repository "deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -cs) main"
  sudo apt install -y google-cloud-sdk
}

iDocker() {
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  sudo apt install -y docker-ce apt-transport-https
  sudo usermod -aG docker $(whoami)
}

iKubectl() {
  curl -sLO https://storage.googleapis.com/kubernetes-release/release/$(
    curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
  )/bin/linux/amd64/kubectl
  chmod +x kubectl
  sudo mv kubectl /usr/local/bin
  kubectl version
}

iStern() {
  curl -sLo stern https://github.com/wercker/stern/releases/download/$(
    git ls-remote --refs --tags https://github.com/wercker/stern.git | sort -t '/' -k 3 -V | tail -1 | awk -F/ '{print $3}'
  )/stern_linux_amd64
  chmod ugo+x stern
  sudo mv stern /usr/local/bin
}

iKind() {
  curl -sLo kind https://github.com/kubernetes-sigs/kind/releases/download/$(
    git ls-remote --tags --refs https://github.com/kubernetes-sigs/kind.git | tail -1 | awk -F/ '{print $3}'
  )/kind-$(uname)-amd64
  chmod +x kind
  sudo mv kind /usr/local/bin
  kind version
}

useFunction() {
  user=$(grep -w 1000 /etc/passwd | awk -F: '{print $1}')
  name=$1
  type $name | tail -$(echo $(type $name | wc -l)-1 | bc) > /tmp/$name
  sudo -u $user bash -c ". /tmp/$name && $name"
  rm /tmp/$name
}

account() {
  user=jobscale
  old=$(grep -w 1000 /etc/passwd | awk -F: '{print $1}')
  sudo usermod -l $user -m -d /home/$user $old
  echo "$user ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/70-users
  sudo systemctl restart sshd
}

system() {
  sudo dd if=/dev/zero of=/var/swapfile bs=16M count=4K
  sudo chmod 0600 /var/swapfile
  sudo mkswap /var/swapfile
  sudo swapon /var/swapfile
  echo '/var/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
  sudo mount -a
}

minimum() {
  export DEBIAN_FRONTEND=noninteractive
  apt update && apt install -y git vim tmux curl zip unzip iproute2 dnsutils procps iputils-ping
}

db() {
  apt install -y mariadb-server
}

cli() {
  apt install -y \
    curl whois nmap traceroute iproute2 \
    nfs-common cifs-utils exfat-utils sshfs \
    git subversion vim tmux dstat peco \
    at expect zip unzip colordiff speedtest-cli \
    mariadb-client libpng-dev nasm
}

account() {
  user=$(grep -w 1000 /etc/passwd | awk -F: '{print $1}')
  echo "$user ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers.d/70-users
}

system() {
  dd if=/dev/zero of=/mnt/swap bs=2M count=512
  chmod 0600 /mnt/swap
  mkswap /mnt/swap
  swapon /mnt/swap
  echo '/mnt/swap none swap sw 0 0' | tee -a /etc/fstab
}

main() {
  date +'START    my-init %Y-%m-%d %H:%M:%S'
  [[ $(id -u) == 0 ]] && alias sudo=''
  echo installing...
  date +'FINISHED my-init %Y-%m-%d %H:%M:%S'
}
