#!/usr/bin/env bash
set -eu

export DEBIAN_FRONTEND=noninteractive

stable() {
  apt update
  apt install -y apt-transport-https
  apt update
  apt upgrade -y
  apt install -y curl git vim tmux \
    iproute2 dnsutils ncat netcat iputils-ping \
    procps whois nmap traceroute  \
    python3-pip unzip zip tree colordiff
  apt autoremove -y

  [[ ! -d ~/_ ]] && git clone https://github.com/jobscale/_.git ~/_
}

# Debian 10
buster() {
  stable
}

# Debian 11
bullseye() {
  stable
}

# Ubuntu 14.04
trusty() {
  stable
}

# Ubuntu 16.04
xenial() {
  stable
}

# Ubuntu 18.04
bionic() {
  stable
}

# Ubuntu 20.04
focal() {
  stable
}

# Ubuntu 21.10
impish() {
  stable
}

# Ubuntu 22.04
jammy() {
  stable
}

{
  date +'BEGIN stable %Y-%m-%d %H:%M:%S'
  which lsb_release && lsb_release -cs
  eval $(cat /etc/*release)
  $VERSION_CODENAME
  date +'END   stable %Y-%m-%d %H:%M:%S'
}
