#!/usr/bin/env bash
set -eux

export DEBIAN_FRONTEND=noninteractive

stable() {
  apt-get update
  apt-get install -y apt-transport-https
  apt-get update
  apt-get full-upgrade -y
  apt-get install -y curl git vim tmux htop expect \
    iproute2 dnsutils ncat netcat iputils-ping \
    nmap traceroute procps whois progress \
    python3-pip bc jq zip unzip tree colordiff \
    openssh-server bash-completion
  apt-get autoremove -y

  [[ ! -d ~/_ ]] && git clone git@github.com:jobscale/_.git ~/_ || echo
}

stable-2023() {
  apt-get update
  apt-get install -y apt-transport-https
  apt-get update
  apt-get full-upgrade -y
  apt-get install -y curl git vim tmux htop expect \
    iproute2 dnsutils ncat netcat-openbsd iputils-ping \
    nmap traceroute procps whois progress \
    python3-pip bc jq zip unzip tree colordiff \
    openssh-server bash-completion
  apt-get autoremove -y

  [[ ! -d ~/_ ]] && git clone git@github.com:jobscale/_.git ~/_ || echo
}

# Debian 12
bookworm() {
  stable-2023
  apt-get install -y network-manager
}

# Debian 11
bullseye() {
  stable
  apt-get install -y network-manager
}

# Debian 10
buster() {
  stable
  apt-get install -y network-manager
}

# Ubuntu 22.04
jammy() {
  stable
}

# Ubuntu 20.04
focal() {
  stable
}

# Ubuntu 18.04
bionic() {
  stable
}

# Ubuntu 16.04
xenial() {
  stable
}

# Ubuntu 14.04
trusty() {
  stable
}

# kali
kali-rolling() {
  stable-2023
}

{
  echo "START  stable $(date --rfc-3339=seconds)"
  which lsb_release && lsb_release -cs || echo "no lsb_release"
  eval $(cat /etc/*release)
  $VERSION_CODENAME
  echo "FINISH stable $(date --rfc-3339=seconds)"
}
