#!/usr/bin/env bash
set -eux

export DEBIAN_FRONTEND=noninteractive

stable() {
  apt-get update
  apt-get install -y apt-transport-https
  apt-get update
  apt-get full-upgrade -y
  apt-get install -y curl git vim tmux htop \
    iproute2 dnsutils ncat netcat iputils-ping \
    procps whois nmap traceroute  \
    python3-pip unzip tree colordiff
  apt-get autoremove -y

  [[ ! -d ~/_ ]] && git clone https://github.com/jobscale/_.git ~/_
}

kali-rolling() {
  apt-get update
  apt-get install -y apt-transport-https
  apt-get update
  apt-get full-upgrade -y
  apt-get install -y curl git vim tmux htop \
    iproute2 dnsutils ncat netcat-openbsd iputils-ping \
    procps whois nmap traceroute  \
    python3-pip unzip tree colordiff
  apt-get autoremove -y

  [[ ! -d ~/_ ]] && git clone https://github.com/jobscale/_.git ~/_
}

# Debian 10
buster() {
  stable
  apt-get install -y network-manager
}

# Debian 11
bullseye() {
  stable
  apt-get install -y network-manager
}

# Ubuntu 14.04
trusty() {
  stable
}

# Ubuntu 16.04
xenial() {
  stable
}

# Ubuntu 18.04
bionic() {
  stable
}

# Ubuntu 20.04
focal() {
  stable
}

# Ubuntu 22.04
jammy() {
  stable
}

{
  date +'BEGIN stable %Y-%m-%d %H:%M:%S'
  which lsb_release && lsb_release -cs || echo "no lsb_release"
  eval $(cat /etc/*release)
  $VERSION_CODENAME
  date +'END   stable %Y-%m-%d %H:%M:%S'
}
