#!/usr/bin/env bash
set -eu

initApt() {
  export DEBIAN_FRONTEND=noninteractive
  apt purge -y nano
  apt update
  apt upgrade -y
  apt install -y vim git tmux iproute2 dnsutils netcat ncat python3-pip
}

netInit() {
  [[ "$(lsb_release -is)" != Ubuntu ]] && return 0
  # rm /etc/resolv.conf
  # with auto
  # ln -sfn /run/systemd/resolve/resolv.conf /etc/resolv.conf
  # with manual
  # ln -sfn /usr/systemd/resolve/resolv.conf /etc/resolv.conf
  systemctl disable systemd-networkd
  systemctl stop systemd-networkd
}

account() {
  user=jobscale
  old=$(grep -w 1000 /etc/passwd | awk -F: '{print $1}')
  usermod -l $user -m -d /home/$user $old
  echo "$user ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers.d/70-users
  systemctl restart sshd
}

busterToBullseye() {
  grep aws.deb /etc/apt/sources.list > /tmp/aws-deb
  sed -e 's/buster/bullseye/g' < /tmp/aws-deb > /etc/apt/sources.list
  echo '
deb http://deb.debian.org/debian bullseye main
deb http://security.debian.org/debian-security bullseye-security main
deb http://deb.debian.org/debian bullseye-updates main
' | tee -a /etc/apt/sources.list
  apt purge -y nano
  apt update
  apt full-upgrade -y
  apt install -y curl git
  curl -sL git.io/ramen | bash
  curl -sL git.io/susi | bash
}

userAdd() {
  useradd --shell $(which bash) --create-home $1
  sudo -u $1 bash -c 'ssh-keygen -q -t ed25519 -N "" -C "$(id -un)@$(hostname)" -f /home/$(id -un)/.ssh/id_ed25519 <<<y && cat /home/$(id -un)/.ssh/id_ed25519.pub > /home/$(id -un)/.ssh/authorized_keys'
  usermod -aG sudo $1
  echo "$1 ALL=(ALL:ALL) NOPASSWD:ALL" | tee -a /etc/sudoers.d/70-users
  GIP=$(curl -s https://inet-ip.info/ip)
  DATA=$(cat /home/$1/.ssh/id_ed25519 | sed -z -e 's/\n/\\n/g')
  curl -is -X POST -H 'Content-Type: application/json' \
  https://tanpo.jsx.jp/api/slack \
  --data "{\"icon_emoji\":\":violin:\",\"username\":\"EC2\",\"text\":\"$GIP\\n$DATA\"}"
}

main() {
  date +'BEGIN $0 user-data %Y-%m-%d %H:%M:%S'
  initApt
  netInit
  account
  date +'END   $0 user-data %Y-%m-%d %H:%M:%S'
}

main | tee /var/log/user-data-init.log
