#!/usr/bin/env bash
set -eu

export DEBIAN_FRONTEND=noninteractive

initApt() {
  apt purge -y nano
  apt update
  apt upgrade -y
  apt install -y vim git tmux iproute2 dnsutils netcat ncat python3-pip
}

netInit() {
  [[ "$(lsb_release -is)" != Ubuntu ]] && return 0
  # rm /etc/resolv.conf
  # with auto
  # ln -sfn /run/systemd/resolve/resolv.conf /etc/resolv.conf
  # with manual
  # ln -sfn /usr/systemd/resolve/resolv.conf /etc/resolv.conf
  systemctl disable systemd-networkd
  systemctl stop systemd-networkd
}

account() {
  user=jobscale
  old=$(grep -w 1000 /etc/passwd | awk -F: '{print $1}')
  usermod -l $user -m -d /home/$user $old
  echo "$user ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers.d/70-users
  systemctl restart sshd
}

main() {
  date +'BEGIN user-data %Y-%m-%d %H:%M:%S'
  initApt
  netInit
  account
  date +'END   user-data %Y-%m-%d %H:%M:%S'
}

main | tee /var/log/user-data-init.log
