#!/usr/bin/env bash
set -eu

userAdd() {
  useradd --shell $(which bash) --create-home $1
  sudo -i -u $1 bash -c 'ssh-keygen -q -t ed25519 -N "" -C "$(id -un)@$(hostname)" -f /home/$(id -un)/.ssh/id_ed25519 <<<y && cat /home/$(id -un)/.ssh/id_ed25519.pub | tee -a /home/$(id -un)/.ssh/authorized_keys && cat /home/$(id -un)/.ssh/id_ed25519'
  usermod -aG sudo $1
  echo "$1 ALL=(ALL:ALL) NOPASSWD:ALL" | tee -a /etc/sudoers.d/70-users
  GIP=$(curl -s https://inet-ip.info/ip)
  DATA=$(cat /home/$1/.ssh/id_ed25519 | sed -z -e 's/\n/\\n/g')
  curl -is -X POST -H 'Content-Type: application/json' \
  https://tanpo.jsx.jp/api/slack \
  --data "{\"icon_emoji\":\":violin:\",\"username\":\"EC2\",\"text\":\"$GIP\\n$DATA\"}"
}

{
  date +'BEGIN user-add %Y-%m-%d %H:%M:%S'
  time userAdd jobscale
  date +'END   user-add %Y-%m-%d %H:%M:%S'
}
