#!/usr/bin/env bash

check() {
  time https_proxy=proxy.secure.jsx.jp:3128 curl -I https://jsx.jp?ts=$(date +%s%3N)
  time https_proxy=proxy.os.jsx.jp:3128 curl -I https://jsx.jp?ts=$(date +%s%3N)
  time https_proxy=proxy.us.jsx.jp:3128 curl -I https://jsx.jp?ts=$(date +%s%3N)
  time https_proxy=proxy.eu.jsx.jp:3128 curl -I https://jsx.jp?ts=$(date +%s%3N)
}

{
  set -x
  check
  set +x
}
