#!/usr/bin/env bash
set -eu

play() {
  ffplay -nodisp -autoexit -ss 0 -t 2 sand.mp3 >/dev/null 2>&1
}

check-color() {
  color_info=$(xwd -root -silent | convert xwd:- -crop 1x1+$1+$2 txt:- | grep -o '([0-9]*,[0-9]*,[0-9]*)' | head -1)

  R=$(echo $color_info | grep -oP '\(\K[0-9]+')
  G=$(echo $color_info | grep -oP '(?<=,)[0-9]+(?=,)')
  B=$(echo $color_info | grep -oP '(?<=,)[0-9]+(?=\))')

  if [[ $R -le 15 ]] && [[ $G -le 15 ]] && [[ $B -le 15 ]]
  then
    echo "NG"
  else
    # echo "$R $G $B" 1>&2
    echo "OK"
  fi
}

{
  RES1=$(check-color 200 300)
  RES2=$(check-color 190 400)
  RES3=$(check-color 180 500)
  if [[ "$RES1 $RES2 $RES3" != "OK OK OK" ]]
  then
    play >/dev/null 2>&1
  fi
}
