#!/usr/bin/env bash
set -eu

play() {
  ffplay -nodisp -autoexit -ss 0 -t 2 sand.mp3 >/dev/null 2>&1
}

screenshot() {
  local AMOUNTS=${2:-0}
  if ! xwd -root -silent > "$1"; then
    echo "xwd failed at attempt $AMOUNTS" 1>&2
    if [[ $AMOUNTS -lt 2 ]]; then
      sleep 0.2
      screenshot $1 $(( AMOUNTS + 1 ))
      return
    fi
    echo "Retry Failed" 1>&2
    exit 1
  fi
}

check-color() {
  color_info=$(convert xwd:$3 -crop 1x1+$1+$2 txt:- | grep -o '([0-9]*,[0-9]*,[0-9]*)' | head -1)
  # xdotool mousemove $1 $2
  # sleep 0.2

  R=$(echo $color_info | grep -oP '\(\K[0-9]+')
  G=$(echo $color_info | grep -oP '(?<=,)[0-9]+(?=,)')
  B=$(echo $color_info | grep -oP '(?<=,)[0-9]+(?=\))')

  if [[ "$R" -ge 15 ]] && [[ "$G" -ge 15 ]] && [[ "$B" -ge 10 ]]
  then
    echo "OK"
    # echo "$R $G $B" 1>&2
  else
    echo "NG"
    # echo "$R $G $B" 1>&2
  fi
}

{
  TEMP_DIR=$(mktemp -d)
  TEMP_FILE=$TEMP_DIR/sc.bmp
  screenshot $TEMP_FILE
  RES2=$(check-color 10 300 $TEMP_FILE)
  RES3=$(check-color 10 400 $TEMP_FILE)
  RES4=$(check-color 10 500 $TEMP_FILE)
  RES1=$(check-color 10 600 $TEMP_FILE)
  rm -fr $TEMP_DIR
  # echo "$RES1 $RES2 $RES3 $RES4" 1>&2
  if [[ "$RES1 $RES2 $RES3 $RES4" != "OK OK OK OK" ]]
  then
    play >/dev/null 2>&1
  else
    echo "ALL OK"
  fi
}
