#!/usr/bin/env bash
set -eu

play() {
  ffplay -nodisp -autoexit -ss 0 -t 2 sand.mp3 >/dev/null 2>&1
}

check-color() {
  color_info=$(xwd -root -silent | convert xwd:- -crop 1x1+$1+$2 txt:- | grep -o '([0-9]*,[0-9]*,[0-9]*)' | head -1)
  # xdotool mousemove $1 $2
  # sleep 0.2

  R=$(echo $color_info | grep -oP '\(\K[0-9]+')
  G=$(echo $color_info | grep -oP '(?<=,)[0-9]+(?=,)')
  B=$(echo $color_info | grep -oP '(?<=,)[0-9]+(?=\))')

  if [[ $R -ge 11 ]] && [[ $G -ge 11 ]] && [[ $B -ge 6 ]]
  then
    echo "OK"
    # echo "$R $G $B" 1>&2
  else
    echo "NG"
    # echo "$R $G $B" 1>&2
  fi
}

{
  RES1=$(check-color 110 200)
  RES2=$(check-color 80 300)
  RES3=$(check-color 50 400)
  RES4=$(check-color 20 500)
  # echo "$RES1 $RES2 $RES3 $RES4" 1>&2
  if [[ "$RES1 $RES2 $RES3 $RES4" != "OK OK OK OK" ]]
  then
    play >/dev/null 2>&1
  else
    echo "ALL OK"
  fi
}
