#!/usr/bin/env bash
set -eu

play() {
  ffplay -nodisp -autoexit -ss 0 -t 2 sand.mp3 >/dev/null 2>&1
}

EXECUTION=$(date +%s)
loop() {
  local end_time=$(( $(date +%s) + $1 ))
  while [ $(date +%s) -lt $end_time ]
  do
    printf '\r%5d ' $(( end_time - $(date +%s) ))
    if [[ $(( $(date +%s) - $EXECUTION )) -ge 100 ]]
    then
      EXECUTION=$(date +%s)
      xdotool mousemove $(( 100 + $(( $(date +%s%3N) % 100 )) )) 400
      sleep 0.2
      xdotool mousemove $(( 100 + $(( $(date +%s%3N) % 100 )) )) 200
    fi
    sleep 1
    while [[ "$(./check-color)"  != "ALL OK" ]]
    do
      sleep 6
    done
  done
  printf '\r%5d\n' 0
}

ADDING=$1
COUNT=$2
DURATION=$3
XX=$4
YY=$5
INTERVAL=8

fire() {
  xdotool mousemove $XX $YY
  sleep 2
  echo -ne "\033[A"
  echo './get-point'
  ./get-point
  xdotool mousedown 1
  sleep 0.2
  xdotool mouseup 1
}

for i in $(seq 1 $COUNT)
do
  INTERVAL=$(( $INTERVAL + $ADDING ))
  WAIT_TIME=$(( $INTERVAL + $DURATION ))
  fire
  echo "Step $i ... next $(( $COUNT - $i ))"
  loop $WAIT_TIME
done

play
