#!/usr/bin/env bash
set -eu

# dependent on bash >= 5.2

play() {
  ffplay -nodisp -autoexit -ss 0 -t 2 sand.mp3 >/dev/null 2>&1
}

EXECUTION=$(date +%s)

loop() {
  local end_time=$(( $(date +%s) + $1 ))
  while [ $(date +%s) -lt $end_time ]
  do
    printf '\r%5d ' $(( end_time - $(date +%s) ))
    if [[ $(( $(date +%s) - EXECUTION )) -ge 100 ]]
    then
      EXECUTION=$(date +%s)
      xdotool mousemove $(( 100 + $(( $(date +%s%3N) % 100 )) )) 400
      sleep 0.2
      xdotool mousemove $(( 100 + $(( $(date +%s%3N) % 100 )) )) 200
    fi
    sleep 1
    while [[ "$(./check-color)"  != "ALL OK" ]]
    do
      sleep 6
    done
  done
  printf '\r%5d\n' 0
}

readonly ADDING=$1
readonly COUNT=$2
DURATION=$3
readonly XX=$4
readonly YY=$5
readonly INTERVAL=8

fire() {
  xdotool mousemove $XX $YY
  sleep 2
  xdotool mousedown 1
  sleep 0.2
  xdotool mouseup 1
}

main() {
  echo
  for i in $(seq 1 $COUNT)
  do
    DURATION=$(( DURATION + ADDING ))
    local WAIT_TIME=$(( INTERVAL + DURATION ))
    fire
    echo -ne "\e[A\r\e[2K"
    echo " Step $i ... ( next time ) ( $(( COUNT - i )) ${DURATION} )"
    printf '%8s ' ' '
    echo -n "  xy $(./get-point)"
    loop $WAIT_TIME
  done
  echo

  play
}

main
