#!/usr/bin/env bash
set -eu

# dependent on bash >= 5.2

play() {
  ffplay -nodisp -autoexit -ss 0 -t 2 sand.mp3 >/dev/null 2>&1
}

readonly FILE_TIME="/tmp/quest-force-time"
readonly FILE_LOG="/tmp/quest-cursor.log"
readonly FILE_COUNT_LEFT="/tmp/quest-count-left"

# next tick emitter
update-time() {
  echo $(cat ${FILE_TIME} 2>/dev/null)
  rm -f ${FILE_TIME}
}

# update count left
update-count() {
  echo $(cat ${FILE_COUNT_LEFT} 2>/dev/null)
  rm -f ${FILE_COUNT_LEFT}
}

# activation per 100 seconds
ACTIVATE=$(date +%s)
loop() {
  local fire_time=$(( $(date +%s) + $1 ))
  while [ $(date +%s) -lt $fire_time ]; do
    printf '\r%5d ' $(( fire_time - $(date +%s) ))
    if [[ $(( $(date +%s) - ACTIVATE )) -ge 100 ]]; then
      ACTIVATE=$(date +%s)
      xdotool mousemove $(( 100 + $(( $(date +%s%3N) % 100 )) )) 400
      sleep 0.2
      xdotool mousemove $(( 100 + $(( $(date +%s%3N) % 100 )) )) 200
    fi
    sleep 1
    while [[ "$(./check-color)"  != "ALL OK" ]]; do
      post-slack "Blocking - building the troops"
      sleep 6
    done
    local FAST_UPDATE=$(update-time)
    if [[ ! -z "$FAST_UPDATE" ]]; then
      fire_time=$(( FAST_UPDATE + 0 ))
    fi
  done
  printf '\r%5d\n' 0
}

readonly ADDING=$1
readonly COUNT=$2
DURATION=$3
if [[ -z "${4:-}" ]]; then
  IFS=, read -r XX YY <<< "$(./get-point)"
else
  IFS=, read -r XX YY <<< "$4"
fi
declare -r XX YY
echo "cursor $XX $YY" >> "${FILE_LOG}"
readonly INTERVAL=8

fire() {
  xdotool mousemove $XX $YY
  sleep 2
  xdotool mousedown 1
  sleep 0.2
  xdotool mouseup 1
}

main() {
  echo
  local total=0
  local count=${COUNT}
  while [[ $count -gt 0 ]]; do
    count=$(( count - 1 ))
    total=$(( total + 1 ))
    DURATION=$(( DURATION + ADDING ))
    local WAIT_TIME=$(( INTERVAL + DURATION ))
    fire
    echo -ne "\e[A\r\e[2K"
    echo " Step $( printf '%3d' ${total} ) ... left - $( printf '%3d %3d' ${count} ${DURATION} )"
    echo -n "$(printf '%8s ' ' ') x,y $(./get-point)"
    loop $WAIT_TIME
    local FAST_UPDATE=$(update-count)
    if [[ ! -z "$FAST_UPDATE" ]]; then
      count=$(( FAST_UPDATE + 0 ))
    fi
  done
  echo

  post-slack "Finish build the troops"
  play
}

main
