#!/usr/bin/env bash
set -eu

EXECUTION=$(date +%s)
loop() {
  local end_time=$(( $(date +%s) + $1 ))
  while [ $(date +%s) -lt $end_time ]
  do
    printf '\r%5d ' $(( end_time - $(date +%s) ))
    if [[ $(( $(date +%s) - $EXECUTION )) -ge 100 ]]
    then
      EXECUTION=$(date +%s)
      xdotool mousemove $(( 200 + $(( $(date +%s%3N) % 100 )) )) 300
      sleep 0.2
      xdotool mousemove $(( 200 + $(( $(date +%s%3N) % 100 )) )) 200
    fi
    ./check-color
    sleep 1
  done
  printf '\r%5d\n' 0
}

while true
do
  echo "./get-point"
  ./get-point
  loop 600
done
