#!/usr/bin/env bash
set -eu

# activation per 100 seconds
ACTIVATE=$(date +%s)
loop() {
  local fire_time=$(( $(date +%s) + $1 ))
  while [ $(date +%s) -lt $fire_time ]; do
    printf '\r%5d ' $(( fire_time - $(date +%s) ))
    if [[ $(( $(date +%s) - $ACTIVATE )) -ge 100 ]]; then
      ACTIVATE=$(date +%s)
      eval $(xdotool getmouselocation --shell)
      xdotool mousemove 10 500
      RES=$(./check-color)
      sleep 0.2
      xdotool mousemove $X $Y
    fi
    sleep 1
  done
  printf '\r%5d\n' 0
}

main() {
  # infinity loop
  while true; do
    echo -n "getting cursor point './get-point' x,y = " && ./get-point
    loop 600
  done
}

main
