apiVersion: batch/v1
kind: CronJob
metadata:
  name: ec-cube-check
  namespace: health-check
spec:
  jobTemplate:
    metadata:
      name: ec-cube-check
    spec:
      template:
        spec:
          containers:
          - image: jobscale/ec-cube
            name: ec-cube-check
            args: ["/bin/cat", "/etc/os-release"]
            imagePullPolicy: Always
          restartPolicy: OnFailure
  schedule: 0/7 * * * *
