kind: PersistentVolume
apiVersion: v1
metadata:
  name: potgres-pv
spec:
  storageClassName: potgres
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/var/lib/potgres/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: potgres-pv-claim
spec:
  storageClassName: potgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
