apiVersion: apps/v1
kind: Deployment
metadata:
  name: wetty
  namespace: standard
spec:
  selector:
    matchLabels:
      app: wetty
  template:
    metadata:
      labels:
        app: wetty
    spec:
      containers:
      - image: ghcr.io/jobscale/wetty:dind
        name: wetty
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: wetty
  namespace: standard
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: wetty
  type: ClusterIP
