apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipcode-jp
spec:
  selector:
    matchLabels:
      app: zipcode-jp
  template:
    metadata:
      labels:
        app: zipcode-jp
    spec:
      containers:
      - image: ghcr.io/jobscale/zipcode-jp
        name: zipcode-jp
---
apiVersion: v1
kind: Service
metadata:
  name: zipcode-jp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: zipcode-jp
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: zipcode-jp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zipcode-jp
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipcode-jp
  labels:
    name: zipcode-jp
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: ["zipcode-jp.jsx.jp"]
  rules:
  - host: zipcode-jp.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: zipcode-jp
            port:
              number: 80
