apiVersion: apps/v1
kind: Deployment
metadata:
  name: kde-lo
spec:
  selector:
    matchLabels:
      app: kde-lo
  template:
    metadata:
      labels:
        app: kde-lo
    spec:
      containers:
      - image: ghcr.io/jobscale/reverse-proxy
        name: kde-lo
        env:
        - name: BACKEND
          value: http://kde.x.jsx.jp:2999
---
apiVersion: v1
kind: Service
metadata:
  name: kde-lo
spec:
  selector:
    app: kde-lo
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kde-lo
  labels:
    name: kde-lo
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - secret'
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: ["kde.jsx.jp", "kde.x.jsx.jp"]
  rules:
  - host: kde.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: kde-lo
            port:
              number: 80
  - host: kde.x.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: kde-lo
            port:
              number: 80
