apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
spec:
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
        image: jobscale/squid
        imagePullPolicy: Always
