apiVersion: v1
kind: Service
metadata:
  name: squid
  labels:
    app: squid
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    nodePort: 30312
    port: 3128
    targetPort: 3128
    protocol: TCP
  selector:
    app: squid
