apiVersion: v1
kind: Service
metadata:
  name: squid
spec:
  selector:
    app: squid
  type: LoadBalancer
  ports:
  - name: tcp
    nodePort: 30312
    port: 3128
    targetPort: 3128
    protocol: TCP
