kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 0.0.0.0
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30443
    hostPort: 4443
    listenAddress: 0.0.0.0
  - containerPort: 30080
    hostPort: 4080
    listenAddress: 0.0.0.0
  - containerPort: 30053
    protocol: TCP
    hostPort: 4053
    listenAddress: 127.0.0.2
  - containerPort: 30053
    protocol: UDP
    hostPort: 4053
    listenAddress: 127.0.0.2
  - containerPort: 30312
    hostPort: 4128
    listenAddress: 0.0.0.0
  extraMounts:
  - containerPath: /var/log
    hostPath: /home/k8s/system/var/log
  - containerPath: /mnt/extra
    hostPath: /home/k8s/mnt/extra
  - containerPath: /mnt/var
    hostPath: /home/k8s/mnt/var
