apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      run: mariadb
  template:
    metadata:
      labels:
        run: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "false"
        resources:
          limits:
            cpu: 200m
            memory: 500M
          requests:
            cpu: 120m
            memory: 300M
