kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb-pv
spec:
  storageClassName: mariadb
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/var/lib/mariadb"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: mariadb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
