apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanpo
  namespace: standard
spec:
  selector:
    matchLabels:
      app: tanpo
  template:
    metadata:
      labels:
        app: tanpo
    spec:
      containers:
      - image: ghcr.io/jobscale/tanpo
        name: tanpo
---
apiVersion: v1
kind: Service
metadata:
  name: tanpo
  namespace: standard
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tanpo
  type: ClusterIP
