apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  labels:
    app: redmine
    component: deployment
spec:
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
        component: workload
    spec:
      containers:
      - name: redmine
        image: redmine:bullseye
        env:
        - name: REDMINE_DB_MYSQL
          value: mysql.mysql.svc.cluster.local
        - name: REDMINE_DB_USERNAME
          value: redmine-user
        - name: REDMINE_DB_PASSWORD
          value: redmine-admin
---
apiVersion: v1
kind: Service
metadata:
  name: redmine
  labels:
    app: redmine
    component: service
spec:
  selector:
    app: redmine
  type: LoadBalancer
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redmine
  labels:
    name: redmine
    component: ingress
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: [ "redmine.jsx.jp" ]
  rules:
  - host: redmine.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: redmine
            port:
              number: 80
