kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 0.0.0.0
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30443
    hostPort: 4443
  - containerPort: 30080
    hostPort: 4080
- role: worker
