apiVersion: gitkube.sh/v1alpha1
kind: Remote
metadata:
  creationTimestamp: null
  name: k8s
spec:
  authorizedKeys:
  - |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHAftPV6QZiSecx1LqiBEoy+2qvpd7YnWuU3iMyfXKa3qLvb1g5WSMEZulpl1HLa8//HsinyXv7BNDgVzmJDPPuuAMETWv0ffH2DtsW1vbaYWr2OxAdaan1Fh1PEW8uRvDbqWkBLpVS7Mp/4dBifDxhtP0yKQAt6OYJtqDy9Grtb1EcMn0HoKOq8/5EBR3GBOM+w7pjX/CMZDKcf7uiQ4MDsp6kwffytoAyYR5E1CwLWwm29MHqvVjTwAIhA8jfw1xlXhMIOIzZ3M6nTqeks6LAhNKzJBXuXKj4XMS7ZHkVOYvJmsIEbgpmIEyhZrcGJGH7j24wWP+SWNYZ38EmCj3 jobscale@pegasus
  deployments:
  - containers:
    - dockerfile: Dockerfile
      name: app
      path: ./
    name: app
  manifests:
    helm: {}
    path: ""
  registry:
    credentials:
      secretKeyRef:
        key: ""
      secretRef: k8s-regsecret
    url: docker.io/
status:
  remoteUrl: ""
  remoteUrlDesc: ""
