apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - min:
      cpu: 30m
      memory: 100M
    defaultRequest:
      cpu: 50m
      memory: 300M
    default:
      cpu: 200m
      memory: 500M
    max:
      cpu: 300m
      memory: 800M
    type: Container
