apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - min:
      cpu: 100m
      memory: 100M
    defaultRequest:
      cpu: 200m
      memory: 200M
    default:
      cpu: 300m
      memory: 300M
    max:
      cpu: 1600m
      memory: 1600M
    type: Container
