apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - default:
      cpu: 20m
      memory: 100M
    defaultRequest:
      cpu: 50m
      memory: 200M
    max:
      cpu: 50m
      memory: 100M
    min:
      cpu: 20m
      memory: 200M
    type: Container
