apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - min:
      cpu: 1000m
      memory: 1000M
    defaultRequest:
      cpu: 2000m
      memory: 2000M
    default:
      cpu: 3000m
      memory: 3000M
    max:
      cpu: 4000m
      memory: 4000M
    type: Container
