apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - default:
      cpu: 100m
      memory: 100Mi
    defaultRequest:
      cpu: 50m
      memory: 50Mi
    max:
      cpu: 110m
      memory: 110Mi
    min:
      cpu: 30m
      memory: 30Mi
    type: Container
