apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - min:
      cpu: 20m
      memory: 100M
    defaultRequest:
      cpu: 21m
      memory: 101M
    default:
      cpu: 49m
      memory: 299M
    max:
      cpu: 50m
      memory: 300M
    type: Container
