kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# the control plane node config
- role: control-plane
  extraMounts:
  - containerPath: /var/log
    hostPath: /k8s/system/var/log
# the workers
- role: worker
  extraMounts:
  - containerPath: /var/log
    hostPath: /k8s/system/var/log
- role: worker
  extraMounts:
  - containerPath: /var/log
    hostPath: /k8s/system/var/log
- role: worker
  extraMounts:
  - containerPath: /var/log
    hostPath: /k8s/system/var/log
- role: worker
  extraMounts:
  - containerPath: /var/log
    hostPath: /k8s/system/var/log
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraVolumes:
    - name: logs
      hostPath: /var/log/pods
      mountPath: /var/log
