apiVersion: v1
kind: Namespace
metadata:
  name: django
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: django
spec:
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - image: ghcr.io/jobscale/django
        name: django
---
apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: django
spec:
  selector:
    app: django
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: django
  namespace: django
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: django
  maxReplicas: 20
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
