apiVersion: apps/v1
kind: Deployment
metadata:
  name: dokuwiki
  labels:
    app: dokuwiki
    component: deployment
spec:
  selector:
    matchLabels:
      app: dokuwiki
  template:
    metadata:
      labels:
        app: dokuwiki
        component: workload
    spec:
      containers:
      - image: jobscale/dokuwiki
        name: dokuwiki
---
apiVersion: v1
kind: Service
metadata:
  name: dokuwiki
  labels:
    app: dokuwiki
    component: service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dokuwiki
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dokuwiki
  labels:
    name: dokuwiki
    component: ingress
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: [ "wiki.jsx.jp" ]
  rules:
  - host: wiki.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: dokuwiki
            port:
              number: 80
