apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - min:
      cpu: 50m
      memory: 50Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    default:
      cpu: 100m
      memory: 200Mi
    max:
      cpu: 2300m
      memory: 1Gi
    type: Container
