apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp
  namespace: standard
spec:
  selector:
    matchLabels:
      app: exp
  template:
    metadata:
      labels:
        app: exp
    spec:
      containers:
      - image: jobscale/node-express-ejs-authorization
        name: exp
---
apiVersion: v1
kind: Service
metadata:
  name: exp
  namespace: standard
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: exp
  type: ClusterIP
