#!/usr/bin/env bash

cleanZombie() {
  PID=$(ps auxf | grep "[s]sh -N -T us-watch" | awk '{print $2}')
  [[ "$PID" == "" ]] || {
    kill $PID
    echo "$(TZ=Asia/Tokyo date -Iseconds) process killing $PID" 1>&2
  }
}

whileCheck() {
  cleanZombie
  while true
  do
    sleep 60
    if ! nc -vz -w 1 us.jsx.jp 443 > /dev/null 2>&1
    then
      echo "$(TZ=Asia/Tokyo date -Iseconds) connection failed" 1>&2
      cleanZombie
      continue
    fi
    if ! timeout 10 curl -I https://www.jsx.jp > /dev/null 2>&1
    then
      echo "$(TZ=Asia/Tokyo date -Iseconds) hangup failed" 1>&2
      cleanZombie
      continue
    fi
  done
}

{
  sleep 10 # wait for resolve
  whileCheck &
  while true
  do
    REMOTE=$(dig +short us.jsx.jp)
    if [[ -z "$REMOTE" ]]
    then
      echo "$(TZ=Asia/Tokyo date -Iseconds) DNS resolve failed" 1>&2
      sleep 300
      continue
    fi
    PRINT="backdoor-k8s - ${REMOTE} from $(hostname) in $(TZ=Asia/Tokyo date -Iseconds)"
    echo "$PRINT"
    CHANNEL=secure timeout 10 $HOME/bin/post-slack "$PRINT"
    ssh-keygen -f "$HOME/.ssh/known_hosts" -R "us.jsx.jp"
    ssh -N -T us-watch
    sleep 60
  done
}
