#!/usr/bin/env bash

cleanZonbi() {
  PID=$(ps auxf | grep "ssh [u]s-watch" | awk '{print $2}')
  [[ "$PID" == "" ]] || kill $PID
}

whileCheck() {
  cleanZonbi
  while true
  do
    sleep 60
    nc -vz -w 1 us.jsx.jp 443
    [[ $(echo $?) == 0 ]] || cleanZonbi && continue
  done
}

{
  whileCheck &
  while true
  do
    REMOTE=$(dig us.jsx.jp | grep -1 "ANSWER SECTION" | tail -1 | awk '{print $5}')
    PRINT="backdoor - ${REMOTE} from $(hostname) connected in $(date -Iseconds)"
    echo "$PRINT"
    CHANNEL=secure timeout 10 post-slack "$PRINT"
    ssh-keygen -f "$HOME/.ssh/known_hosts" -R "us.jsx.jp"
    ssh us-watch
    sleep 300
  done
}
