apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jsxjp-ingress
  namespace: ingress-nginx
spec:
  rules:
  - host: jsx.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: jsxjp
          servicePort: 443
