apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-lo
spec:
  selector:
    matchLabels:
      app: www-lo
  template:
    metadata:
      labels:
        app: www-lo
    spec:
      containers:
      - image: ghcr.io/jobscale/reverse-proxy
        name: www-lo
        env:
        - name: BACKEND
          value: http://www.x.jsx.jp:3000
---
apiVersion: v1
kind: Service
metadata:
  name: www-lo
spec:
  selector:
    app: www-lo
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-lo
  labels:
    name: www-lo
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: ["lo.x.jsx.jp"]
  rules:
  - host: lo.x.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: www-lo
            port:
              number: 80
