---
apiVersion: v1
kind: Namespace
metadata:
  name: net-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  namespace: net-apps
spec:
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - image: jobscale/squid
        name: squid
---
apiVersion: v1
kind: Service
metadata:
  name: squid
  namespace: net-apps
spec:
  loadBalancerSourceRanges:
  - 49.135.0.0/16
  ports:
  - name: tcp
    nodePort: 30312
    port: 3128
    protocol: TCP
    targetPort: 3128
  selector:
    app: squid
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: squid
  namespace: net-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: squid
  maxReplicas: 20
  minReplicas: 2
  targetCPUUtilizationPercentage: 50
