#!/usr/bin/env bash
set -eu

WORKDIR="${HOME:-/tmp}/.work"

n100-cpu() {
  if ! timeout 6 ssh n100 bin/remote-sensors > ${WORKDIR}/.n100-cpu; then
    echo "$(TZ=Asia/Tokyo date -Iseconds) [FAIL]: n100-cpu" 1>&2
  fi
  echo 'not' >> ${WORKDIR}/.n100-cpu
  mv ${WORKDIR}/.n100-cpu ${WORKDIR}/n100-cpu
}

mac-cpu() {
  if ! timeout 10 ssh mac bin/remote-sensors > ${WORKDIR}/.mac-cpu; then
    echo "$(TZ=Asia/Tokyo date -Iseconds) [FAIL]: mac-cpu" 1>&2
  fi
  echo 'not' >> ${WORKDIR}/.mac-cpu
  mv ${WORKDIR}/.mac-cpu ${WORKDIR}/mac-cpu
}

dark-cpu() {
  /opt/_/bin/remote-sensors > ${WORKDIR}/.dark-cpu
  echo 'not' >> ${WORKDIR}/.dark-cpu
  mv ${WORKDIR}/.dark-cpu ${WORKDIR}/dark-cpu
}

main() {
  mkdir -p "${WORKDIR}"
  local STEP=0
  while true
  do
    dark-cpu
    n100-cpu
    if (( STEP == 0 )); then
      mac-cpu
    fi
    (( STEP = (STEP + 1) % 3 )) || :
    sleep 2.2
  done
}

main
