---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
  namespace: net-apps
spec:
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
        component: workload
    spec:
      containers:
      - name: bind9
        image: ghcr.io/jobscale/bind9
---
apiVersion: v1
kind: Service
metadata:
  name: bind9
  namespace: net-apps
spec:
  selector:
    app: bind9
  type: LoadBalancer
  ports:
  - name: udp
    nodePort: 30053
    port: 53
    targetPort: 53
    protocol: UDP
  - name: tcp
    nodePort: 30053
    port: 53
    targetPort: 53
    protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bind9
  namespace: net-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bind9
  maxReplicas: 20
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
