apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-aws
  name: node-aws
spec:
  selector:
    matchLabels:
      app: node-aws
  template:
    metadata:
      labels:
        app: node-aws
    spec:
      containers:
      - image: ghcr.io/jobscale/node-aws:dind
        name: node-aws
        command:
        - bash
        - -c
        - "sudo /etc/init.d/docker start && tail -f /var/log/faillog"
        securityContext:
          privileged: true
