apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramen-timer
  labels:
    app: ramen-timer
    component: deployment
spec:
  selector:
    matchLabels:
      app: ramen-timer
  template:
    metadata:
      labels:
        app: ramen-timer
        component: workload
    spec:
      containers:
      - image: ghcr.io/jobscale/ramen-timer
        name: ramen-timer
---
apiVersion: v1
kind: Service
metadata:
  name: ramen-timer
  labels:
    app: ramen-timer
    component: service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ramen-timer
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ramen-timer
  labels:
    app: ramen-timer
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ramen-timer
  maxReplicas: 3
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ramen-timer
  labels:
    name: ramen-timer
    component: ingress
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: [ "ramen-timer.jsx.jp" ]
  rules:
  - host: ramen-timer.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ramen-timer
            port:
              number: 80
