apiVersion: apps/v1
kind: Deployment
metadata:
  name: kde-lo
  labels:
    app: kde-lo
    component: deployment
spec:
  selector:
    matchLabels:
      app: kde-lo
  template:
    metadata:
      labels:
        app: kde-lo
        component: workload
    spec:
      containers:
      - image: ghcr.io/jobscale/reverse-proxy
        name: kde-lo
        env:
        - name: BACKEND
          value: http://kde.x.jsx.jp:2999
---
apiVersion: v1
kind: Service
metadata:
  name: kde-lo
  labels:
    app: kde-lo
    component: service
spec:
  selector:
    app: kde-lo
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kde-lo
  labels:
    app: kde-lo
    component: middleware
spec:
  basicAuth:
    secret: basic-auth
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kde-lo
  labels:
    app: kde-lo
    component: ingress
spec:
  entryPoints: [ web, websecure ]
  tls:
    secretName: jsxjp-tls
  routes:
  - match: Host(`kde.jsx.jp`)
    kind: Rule
    middlewares:
    - name: kde-lo
    services:
    - name: kde-lo
      port: 80
  - match: Host(`kde.x.jsx.jp`)
    kind: Rule
    middlewares:
    - name: kde-lo
    services:
    - name: kde-lo
      port: 80
