#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides:          backdoor-os
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: backdoor-os daemon
# Description:       This script runs a simple while backdoor-os.
### END INIT INFO

DAEMON_NAME="backdoor-os"
DAEMON_PATH="/usr/local/bin/backdoor-os"
PIDFILE="/var/run/$DAEMON_NAME.pid"
LOG_DIR="/var/log/$DAEMON_NAME"

case "$1" in
  start)
    echo "Starting $DAEMON_NAME..."
    if [ -f $PIDFILE ]; then
        echo "$DAEMON_NAME is already running."
        exit 1
    fi
    mkdir -p $LOG_DIR
    nohup bash -c "sudo -u jobscale $DAEMON_PATH" > $LOG_DIR/$DAEMON_NAME-service.log 2>&1 &
    echo $! > $PIDFILE
    echo "$DAEMON_NAME started. PID $(cat $PIDFILE)"
    ;;
  stop)
    echo "Stopping $DAEMON_NAME..."
    if [ ! -f $PIDFILE ]; then
        echo "$DAEMON_NAME is not running."
        exit 1
    fi
    kill "$(cat $PIDFILE)" && rm -f $PIDFILE
    echo "$DAEMON_NAME stopped."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    if [ -f $PIDFILE ]; then
        echo "$DAEMON_NAME is running with PID $(cat $PIDFILE)."
    else
        echo "$DAEMON_NAME is not running."
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
