apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-prometheus
spec:
  selector:
    matchLabels:
      app: es-prometheus
  template:
    metadata:
      labels:
        app: es-prometheus
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.9.3
        env:
        - name: discovery.type
          value: single-node
        - name: network.host
          value: 127.0.0.1
        - name: http.port
          value: '9201'
      - name: prometheus-exporter
        image: justwatch/elasticsearch_exporter:1.1.0
        args:
        - '--es.uri=http://127.0.0.1:9201'
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: certs
          mountPath: /certs
          readOnly: true
        ports:
        - name: https
          containerPort: 9200
      volumes:
      - name: nginx-config
        configMap:
          name: conf-nginx
      - name: certs
        configMap:
          name: conf-tls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-nginx
data:
  elasticsearch.conf: |
    server {
      listen 9200 ssl;
      server_name _;
      ssl_certificate /certs/tls.crt;
      ssl_certificate_key /certs/tls.key;

      location / {
        proxy_pass http://127.0.0.1:9114;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-tls
data:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFfzCCA2egAwIBAgIUakJ1KPziJL1SNCkp7OVzuRRjOV0wDQYJKoZIhvcNAQEL
    BQAwTzELMAkGA1UEBhMCSkExDjAMBgNVBAgMBU9zYWthMQ4wDAYDVQQHDAVPc2Fr
    YTEPMA0GA1UECgwGanN4LmpwMQ8wDQYDVQQDDAZqc3guanAwHhcNMjIwNDE2MTIy
    NzMzWhcNMjMwNDE2MTIyNzMzWjBPMQswCQYDVQQGEwJKQTEOMAwGA1UECAwFT3Nh
    a2ExDjAMBgNVBAcMBU9zYWthMQ8wDQYDVQQKDAZqc3guanAxDzANBgNVBAMMBmpz
    eC5qcDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAN/lsj8Fd1Lqs7Al
    UiUr4pAFrZjDGYoQxzQdrdQ4QkqN6Prglt3nNEY+8aNHiYVSR3bQyZOU7BfJ1TXa
    uwLoLUJAc3zKDmr6ReMG5OGJFi4fh+su6M9Bg0OIv+8xFHLx/27zioIYq/Dem1mo
    ebMJgPsh394nQ2Skprb6FipdvcIVZB74l/RVlQd6JxcooCTk2/inA7fKxBpdWfjH
    le1AdkvJwGaPimYgjILtpD9uRC/M/MX1waH2xxj1TnU91YyTd0vUwLIOliscPDpQ
    azIsvRotclpvoo/x8isaS9wy+j0VVJedQmLEcL9jiURDldDVkISfFbNlON+BxLLf
    z14hsIuj9TjtO2qLSgHFkMaudrPMtyGEeeU552KeQzpR1yPX9xwVrf7ZKMnUq5fn
    vHulzI1CE601Gta9pAMxK88j/ny2iGm47W+ssvFDqtjfeptx091NZ6PrHXKXoRRh
    obt4U+wu4URlC6PoTWUK1/CBhHljCzrsyHGFte8bnChtCSQmI8IiTEf9rHE1ANZf
    Ypf8YAFSxlsHJXTS96GwFB+eTRcCzgJy1HSSYiCEUEPcLveyKQI0eeH/UII2qoBK
    zYRCD16CsZ1rHaAPTNwrvCtuP2RmX/JNzhNYIk+8/SYiG5j1ruGoqfTNQAzKZeQB
    j+vrKwi3DJ5hlAHcklu7SPNzMz7DAgMBAAGjUzBRMB0GA1UdDgQWBBTw+WVUP1IA
    ntJDO0WpxKUsPp+2QjAfBgNVHSMEGDAWgBTw+WVUP1IAntJDO0WpxKUsPp+2QjAP
    BgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQAFtl43gP7m9WxqS5EQ
    X+QfeL8M39bOPUlqmQdJeWFygHliuIk+LQgF+I9a+EHTlc6SUK9FV/d2BDpikUaR
    BA3NWWUEcMFkyXFExOo27vdF20gquGxwF0QFvrpU5nf04n9LLKE+nI54FejbmZJt
    01/zuxQvq1tgJBu+ywDnVp1jHK1AiY8vuEESNJsUfXEu6UnI8ZQt36vjNxEnWUv3
    ohuTGTmLSa9pSgz4IGEe5r/SGfn5Tftm0DJpNc92LlKdnV3fP8fbiDOiEZ9PlhMM
    3TC7aqGGE3MMFig/DnWsL8Y1+DnhNdnPOmQnWFySLPESfGsiQWpPL3KIa7pgOlpw
    OEQ9Y0YfMEfrTKKBff4L80t/ZKkq8V7Id75JeCxAyEvHPOgB7kb8/+hxghvhJx6a
    ITelYON0clKxNLaHoH5zRtGIfhn0UVxMgw6ZmesnGcvMIAZF2Mr5fCHCWxxkORSJ
    IXze8pxdWbtr34oKbmw3FE2fb6IVQmZfVYnMLm8nInIfhC4zwD5X4G7xqXpoj7wZ
    0er2n6NGUmFoouESGsB+Gaf7yQkfgrvtET3CzuwdcV3GBTwN8bG4YMTx8waCkUxY
    rOfMTDc3iK3fnPQFJGr1knMi7A+gnfjF68l9uwCzEAzCq1XybXsyWUg/nvdGrgW5
    6IRTGvMjLKQm2Uz6Efhlnyusbw==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQDf5bI/BXdS6rOw
    JVIlK+KQBa2YwxmKEMc0Ha3UOEJKjej64Jbd5zRGPvGjR4mFUkd20MmTlOwXydU1
    2rsC6C1CQHN8yg5q+kXjBuThiRYuH4frLujPQYNDiL/vMRRy8f9u84qCGKvw3ptZ
    qHmzCYD7Id/eJ0NkpKa2+hYqXb3CFWQe+Jf0VZUHeicXKKAk5Nv4pwO3ysQaXVn4
    x5XtQHZLycBmj4pmIIyC7aQ/bkQvzPzF9cGh9scY9U51PdWMk3dL1MCyDpYrHDw6
    UGsyLL0aLXJab6KP8fIrGkvcMvo9FVSXnUJixHC/Y4lEQ5XQ1ZCEnxWzZTjfgcSy
    389eIbCLo/U47Ttqi0oBxZDGrnazzLchhHnlOedinkM6Udcj1/ccFa3+2SjJ1KuX
    57x7pcyNQhOtNRrWvaQDMSvPI/58tohpuO1vrLLxQ6rY33qbcdPdTWej6x1yl6EU
    YaG7eFPsLuFEZQuj6E1lCtfwgYR5Yws67MhxhbXvG5wobQkkJiPCIkxH/axxNQDW
    X2KX/GABUsZbByV00vehsBQfnk0XAs4CctR0kmIghFBD3C73sikCNHnh/1CCNqqA
    Ss2EQg9egrGdax2gD0zcK7wrbj9kZl/yTc4TWCJPvP0mIhuY9a7hqKn0zUAMymXk
    AY/r6ysItwyeYZQB3JJbu0jzczM+wwIDAQABAoICABgp8RfOHjerruLm1DvAxb3n
    bvnarInzD5y3S0hpHfZv5GIXFREz37dpGakWkmf6Hk5bcDXmT6itlr4uMhq5NhE9
    ZXllUTMIebxrxQ32PpeRvZiLQoMDvgfu3VASSvOw3HF8BUnPIddoHvoJLcE92FbC
    LCgMssBM6NU8nmHKJi2pI1oYWEX9ao0ZCNj+AHKa5Iasd8FBN/Lkek5YM/0cBOhf
    CM3I1hX5k1CaFyzlWKSUCf/Paytwt8Igz2vl1YNLcweTGYzd+CUE8hcVEMykeXA2
    0W2jOLcyVIGEYAWO1uT6xVtrlHuWWdi+BFWCucuFEQjPJodq+D1fAvyPHRE6r5Pe
    2rhZTph9gMlbqf86fDSCuhOwMGSTWbBlwS4VcYoPfJBQlTiHpMdo5SgMP7xC3eoG
    p3qMtmM7MdQh0COP+jIQr9oAXZR3e2kzqglMLjqcfZnzSdkeGmV2oRbDFa2NNATk
    xokNvy1zB796NnzT93EDEGWQv3+Lz83pr/FBBwKn+iM1jMfdeCpzu6lUABaeEu/r
    ansnrlsN3Jv7nCcpgKHjJ/j9JM9WMEAsUiishlyQlFFxQWUZVi8Lovqm5hEXB9Q6
    oqsNpy5CHCjTCBzPMOR5NIlAjyXq5d/RzkBuvAMRV6YIJyAxn1RcEzM5TFI1YcdO
    Af77kujn3V7R/fNrrYKBAoIBAQDycpFzP3djeWs/PWXo4ptSYHUqVwpdd8FJoTaw
    3Lj3M3g6kUXt0D5oNbUjy3Cav6By0yIMu+tnuOkuDbR6olYk74ZV1fS7G8/Z/e9p
    qDfIAVOM1cTIzGncnJH80mc0MIORap3Kb6thNX/4m92RmFnaWruBre5w+kNz5k8B
    q/x3n0PNwumAVMbOht8xEZvuHwTlrVF7FN5eXwJjU9oqGPKGNJ7dLCQVbppUJjH7
    xn2hv45gVGq+uygFlmgkf7tSkPGsfQR1OpWprMZ3lA2cpZk7CYAaCD/8W/E4dZ84
    WTF8buxRM5cFE2uuih0DYl1kT42aS4ilakwncbtqpYjdAfMDAoIBAQDsaaxKELuF
    lVft097aqfT5W7BusP9IET7Uqo/SXESMMUdf/0Gg/gWEi5FsQFyjh4SWJ+yfBFPq
    RnrFirVsPLJRZGHOBhz7Xf3eGlPmHNkM8zSOOzVi1PDOLjDOaHFe1C0xJ9OVNT7F
    z3PJFoDOQJCDY+y4DLYjtGfPT9IStxvGO2k9jcUN5mriLu7nnUuaqpmtHEYqiixB
    I/mGAUiwCi36KUE7eCi2AgZd1EEMfbgs1BRBfobAxbGSCpCbi9uk7+uI+KKmG1yV
    PdIM3tRVgJ1hX/wZDA+VZzm4UgYQJSYFqBMsNHHOar0k/s1hlUU1Ypq3p1Cso70Q
    JTK03iTtPdlBAoIBAQCPf+xDMH9zqzwlNCwLiYSxX1I5+0axR95pvDfoutvnxNkW
    oUGonqcxewh55UIC9gT7safnrZqJy9KIZag7JbajKfpy965gyPdfaYO5H83UXaSc
    KTLOPt8xqqJl6AsZwtU8zsQSO8JOSSIzfd3I/UnBig6NlOsah6ZBBUIiFS/bhbLW
    KNWYFZWOTBnyqx+F82osn0co+JMdfFKng8wPOrDhamfVNPkujkZeJDVVdoiJoh2d
    Opnrxk7L79g4Mjonho7kryJiWIiY4yCdSk48N2/Yl6jwv41PywOdjVDuQyydH/JT
    pZtvb60+o5TEmgX5B3UirC526dGlTxXE67F0TmENAoIBAQCOuxHwuX9tnAe1J5hB
    biDft5KikaveR8MmRD+GonwkI9BSzdpCp3qPVnAa6hTEChprSXlbXBKJu7l9sEvu
    KAsEhtVhvGEdBdcyk7SZlksYvXC6ela175fe8xY2V+oydWk/Zysfx0C5zpC6FCL5
    4xMcsGSHje0dS1rtV+Sdtf1HxjC4n/IbfUSEgA9uuJGftGYJlKtsHXWwclbAp9/J
    oKu3f9bJX7c8g6ZyWaZYM0LRlc0Q6aHTmselQ0mhD2QxhUQvsuUH4jcYR3WcnZ+W
    a4sY8glS2exCqEq51JOihbsZ6SqCIrufAuRlBIzc4HEjVP/R52sWf9iyebLObdvf
    e9rBAoIBAQDGJsOZGx1DcNAOqYifgGjv3tFeDS9BUc06+8e9/wdWTbTr+hf64sAe
    gGfVae09MZsH84MJXwRD57s86ZBW/CWRvn4avTFCb631ESMCt48NMW6z4iNANuNI
    d5HjsbJSvTnVZFi3eJYqudRZT6gz2UucquedtHy9DQmCFp6YL7BXfwlWE9FXPR7p
    gK1EKe51qN1dLxu+06Ke3P17zfyXP9qp6xb/dhoqnMRDQusYeDHi/jT0ZR2iJa/X
    GBkX0s0AR2mDaS8p52tE9q2HhqmwSc2Dk2ntB60KGWURNe9SOMtc8/mg68Gir3NN
    cBCpjSV7HztgvBukhuhHxv8ViA9XOPO/
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Service
metadata:
  name: es-prometheus
spec:
  selector:
    app: es-prometheus
  type: ClusterIP
  ports:
  - name: https
    port: 9200
    targetPort: https
