---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-nodejs
  labels:
    app: dns-nodejs
    component: autoscaler
spec:
  selector:
    matchLabels:
      app: dns-nodejs
  template:
    metadata:
      labels:
        app: dns-nodejs
        component: workload
    spec:
      containers:
      - name: dns-nodejs
        image: ghcr.io/jobscale/dns-nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: dns-nodejs
  labels:
    app: dns-nodejs
    component: service
spec:
  selector:
    app: dns-nodejs
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: udp
    nodePort: 30053
    port: 53
    targetPort: 53
    protocol: UDP
  - name: tcp
    nodePort: 30053
    port: 53
    targetPort: 53
    protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dns-nodejs
  labels:
    app: dns-nodejs
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dns-nodejs
  maxReplicas: 20
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
