---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  labels:
    app: squid
    component: deployment
spec:
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
        component: workload
    spec:
      containers:
      - image: ghcr.io/jobscale/squid:secure
        name: squid
---
apiVersion: v1
kind: Service
metadata:
  name: squid
  labels:
    app: squid
    component: service
spec:
  selector:
    app: squid
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  ports:
  - name: tcp
    nodePort: 30312
    port: 3128
    protocol: TCP
    targetPort: 3128
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: squid
  labels:
    app: squid
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: squid
  maxReplicas: 20
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
