#!/usr/bin/env bash

if [[ "$(uname -s)" == "Darwin" ]]; then
  PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
fi
TICK_FILE="/tmp/tick-bastion"

updateNextTick() {
  (
    flock -x 200
    printf '%s\n' $(( $(date +%s) + 10 )) > "$TICK_FILE"
  ) 200>"$TICK_FILE"
}

clearTick() {
  (
    flock -x 200
    : > "$TICK_FILE"
  ) 200>"$TICK_FILE"
}

getNextTick() {
  # The INFINITE if without TICK_FILE
  [[ -f "$TICK_FILE" ]] || { echo 9223372036854775807; return; }
  (
    flock -s 200
    [[ -s "$TICK_FILE" ]] && cat "$TICK_FILE" || echo 9223372036854775807
  ) 200<"$TICK_FILE"
}

nextTime() {
  while [[ $(getNextTick) -ge $(date +%s) ]]; do
    sleep 1
  done
}

cleanZombie() {
  local PID=$(pgrep -f "ssh -N -T revers-rem-watch")
  if [[ ! -z "$PID" ]]; then
    echo "$(TZ=Asia/Tokyo date -Iseconds) process killing $PID" 1>&2
    kill $PID
  else
    echo "$(TZ=Asia/Tokyo date -Iseconds) ssh process notfound" 1>&2
  fi
}

whileCheck() {
  cleanZombie
  while true; do
    sleep 60
    nextTime
    if ! nc -vz -w 2 os.jsx.jp 80 > /dev/null 2>&1; then
      echo "$(TZ=Asia/Tokyo date -Iseconds) connection failed" 1>&2
      cleanZombie
      continue
    fi
    if ! timeout 20 ssh -T -p 80 os.jsx.jp echo health-check > /dev/null 2>&1; then
      echo "$(TZ=Asia/Tokyo date -Iseconds) hangup failed" 1>&2
      cleanZombie
      continue
    fi
  done
}

waitForPort() {
  clearTick
  while nc -vz -w 1 os.jsx.jp 80 > /dev/null 2>&1; do
    echo "$(TZ=Asia/Tokyo date -Iseconds) wait for terminate zombie" 1>&2
    local PID=$(ssh bastion sudo ss -tunlp sport = :80 | awk -F 'pid=' '/pid=/ {print $2}' | awk -F, '{print $1}' | head -n1)
    if [[ ! -z "$PID" ]]; then
      ssh bastion sudo kill $PID
    fi
    sleep 5
  done
  updateNextTick
}

waitForResolver() {
  clearTick
  while true; do
    local REMOTE=$(dig +short bastion.jsx.jp)
    if [[ ! -z "$REMOTE" ]]; then
      break
    fi
    echo "$(TZ=Asia/Tokyo date -Iseconds) DNS resolve failed" 1>&2
    sleep 300
  done
  PRINT="reverse-bastion - ${REMOTE} from $(hostname) in $(TZ=Asia/Tokyo date -Iseconds)"
  echo "$PRINT"
  CHANNEL=infra timeout 10 $HOME/bin/post-slack "$PRINT"
  echo "GlobalIP $(curl -s https://inet-ip.info/ip)"
}

{
  sleep 10 # wait for resolver
  whileCheck &
  while true; do
    waitForResolver
    # ssh-keygen -f "$HOME/.ssh/known_hosts" -R "bastion.jsx.jp" > /dev/null 2>&1
    waitForPort
    ssh -N -T revers-rem-watch
    echo "$(TZ=Asia/Tokyo date -Iseconds) SSH broken pipe" 1>&2
    sleep 11.1
  done
}
