apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      return 301 $scheme://jsxjp.awsapps.com/mail$request_uri;
  name: ingress-redirect-mail
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mail.jsx.jp
    secretName: jsxjp-tls
  rules:
  - host: mail.jsx.jp
