#!/usr/bin/env bash

cleanZombie() {
  echo "$(TZ=Asia/Tokyo date -Iseconds) $1" 1>&2
  local PID=$(ps -ax | pgrep -f "ssh -N -T mac-watch")
  echo "$(TZ=Asia/Tokyo date -Iseconds) cleanZombie $PID" 1>&2
  [[ -z "$PID" ]] || kill $PID
}

whileCheck() {
  cleanZombie "initialize clean"
  while true
  do
    sleep 300
    echo -e "\n\r"
    nc -vz -w 2 vpn.jsx.jp 2088 || cleanZombie "connection failed"
    echo -e "\r"
    timeout 10 sudo -u jobscale ssh mac date || cleanZombie "hangup failed"
  done
}

{
  echo "Start bastion"
  sleep 10
  whileCheck &
  while true
  do
    sleep 10
    PRINT="$(TZ=Asia/Tokyo date -Iseconds) mac"
    echo -e "\n$PRINT\n"
    timeout 10 /Users/jobscale/bin/post-slack "$PRINT"
    sudo -u jobscale ssh -N -T mac-watch
    sleep 10
  done
}
