apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine:bullseye
        env:
        - name: REDMINE_DB_MYSQL
          value: mysql.mysql.svc.cluster.local
        - name: REDMINE_DB_USERNAME
          value: redmine-user
        - name: REDMINE_DB_PASSWORD
          value: redmine-admin

---
apiVersion: v1
kind: Service
metadata:
  name: redmine
spec:
  selector:
    app: redmine
  type: ClusterIP
  ports:
  - name: tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
