apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-web
spec:
  selector:
    matchLabels:
      app: mqtt-web
  template:
    metadata:
      labels:
        app: mqtt-web
    spec:
      containers:
      - name: mqtt-web
        image: ghcr.io/jobscale/mqtt-c-pub-sub
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-web
spec:
  selector:
    app: mqtt-web
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mqtt-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mqtt-web
  maxReplicas: 20
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
