apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddb
spec:
  selector:
    matchLabels:
      app: ddb
  template:
    metadata:
      labels:
        app: ddb
    spec:
      containers:
      - image: amazon/dynamodb-local
        name: ddb
---
apiVersion: v1
kind: Service
metadata:
  name: ddb
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: ddb
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ddb
  labels:
    name: ddb
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: ["ddb.jsx.jp"]
  rules:
  - host: ddb.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ddb
            port:
              number: 80
