apiVersion: v1
kind: LimitRange
metadata:
  name: jsxjp
  component: limits
  limits:
  - min:
      cpu: 50m
      memory: 50Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    default:
      cpu: 100m
      memory: 200Mi
    max:
      cpu: 2300m
      memory: 1Gi
    type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsxjp
  component: deployment
spec:
  selector:
    matchLabels:
      app: jsxjp
  template:
    metadata:
      labels:
        app: jsxjp
    spec:
      containers:
      - image: ghcr.io/jobscale/jsxjp
        name: jsxjp
---
apiVersion: v1
kind: Service
metadata:
  name: jsxjp
  component: service
spec:
  selector:
    app: jsxjp
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jsxjp
  component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jsxjp
  maxReplicas: 20
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jsxjp
  labels:
    name: jsxjp
    component: ingress
spec:
  ingressClassName: traefik
  tls:
  - secretName: jsxjp-tls
    hosts: [ "jsx.jp", "www.jsx.jp", "mail.jsx.jp" ]
  rules:
  - host: jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: jsxjp
            port:
              number: 80
  - host: www.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: jsxjp
            port:
              number: 80
  - host: mail.jsx.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jsxjp
            port:
              number: 80
