apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-aws-pv
spec:
  storageClassName: ssd.sda
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/extra/home/store"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-aws-pv-claim
spec:
  storageClassName: ssd.sda
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-aws
  name: node-aws
spec:
  selector:
    matchLabels:
      app: node-aws
  template:
    metadata:
      labels:
        app: node-aws
    spec:
      containers:
      - image: ghcr.io/jobscale/node-aws:dind
        name: node-aws
        securityContext:
          privileged: true
        args: ["tail", "-f", "/var/log/alternatives.log"]
        volumeMounts:
        - name: node-aws-persistent-storage
          mountPath: /home/store
      volumes:
      - name: node-aws-persistent-storage
        persistentVolumeClaim:
          claimName: node-aws-pv-claim
