kind: PersistentVolume
apiVersion: v1
metadata:
  name: node-aws-pv
spec:
  storageClassName: node-aws
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/extra/home/store"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-aws-pv-claim
spec:
  storageClassName: node-aws
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
