apiVersion: apps/v1
kind: Deployment
metadata:
  name: lo-stack
  labels:
    app: lo-stack
    component: deployment
spec:
  selector:
    matchLabels:
      app: lo-stack
  template:
    metadata:
      labels:
        app: lo-stack
        component: workload
    spec:
      containers:
      - image: ghcr.io/jobscale/reverse-proxy
        name: lo-stack
        env:
        - name: BACKEND
          value: http://lo-stack.x.jsx.jp:4566
        - name: HEADERS
          value: '{"authorization":"AWS4-HMAC-SHA256 Credential="}'
---
apiVersion: v1
kind: Service
metadata:
  name: lo-stack
  labels:
    app: lo-stack
    component: service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: lo-stack
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lo-stack
  labels:
    name: lo-stack
    component: ingress
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: [ "lo-stack.jsx.jp" ]
  rules:
  - host: lo-stack.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: lo-stack
            port:
              number: 80
