apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
  labels:
    app: shop
    component: deployment
spec:
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
        component: workload
    spec:
      containers:
      - image: ghcr.io/jobscale/ec-cube
        name: shop
---
apiVersion: v1
kind: Service
metadata:
  name: shop
  labels:
    app: shop
    component: service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: shop
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shop
  labels:
    app: shop
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shop
  maxReplicas: 5
  minReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop
  labels:
    name: shop
    component: ingress
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: [ "shop.jsx.jp" ]
  rules:
  - host: shop.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: shop
            port:
              number: 80
