apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
    component: deployment
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        component: workload
    spec:
      containers:
      - name: web
        image: ghcr.io/jobscale/web
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    component: service
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
  - name: http
    nodePort: 30080
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    nodePort: 30443
    port: 443
    targetPort: 443
    protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web
  labels:
    app: web
    component: workload
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  maxReplicas: 20
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
