name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        imag: web
        tag: $(date +%s)
      run: docker build . -t ${img}:${tag}
      run: docker run --rm --name ${img} -d ${img}:${tag}
      run: docker run --rm --link ${img} -it node curl ${img}
