name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: tag=$(date +%s) img=web && docker build . -t ${img}:${tag} && docker run --rm --name ${img} -d ${img}:${tag} && sleep 3.0 && docker run --rm --link ${img} -it node curl ${img}
