apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: jsxjp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jsxjp
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
