apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jsxjp
spec:
  maxReplicas: 20
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: jsxjp
  targetCPUUtilizationPercentage: 50
