apiVersion: v1
kind: Namespace
metadata:
  name: jsxjp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsxjp
  namespace: jsxjp
spec:
  selector:
    matchLabels:
      app: jsxjp
  template:
    metadata:
      labels:
        app: jsxjp
    spec:
      containers:
      - image: jobscale/jsxjp
        name: jsxjp
---
apiVersion: v1
kind: Service
metadata:
  name: jsxjp
  namespace: jsxjp
spec:
  selector:
    app: jsxjp
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jsxjp
  namespace: jsxjp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jsxjp
  maxReplicas: 20
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
