apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsxjp
spec:
  selector:
    matchLabels:
      app: jsxjp
  template:
    metadata:
      labels:
        app: jsxjp
    spec:
      containers:
      - image: jobscale/jsxjp
        name: jsxjp
        ports:
        - containerPort: 443
          protocol: TCP
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 500M
          requests:
            cpu: 120m
            memory: 300M
