apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsxjp
spec:
  selector:
    matchLabels:
      app: jsxjp
  template:
    metadata:
      labels:
        app: jsxjp
    spec:
      containers:
      - image: jobscale/jsxjp
        imagePullPolicy: Always
        name: jsxjp
        ports:
        - containerPort: 443
          protocol: TCP
        - containerPort: 80
          protocol: TCP
