apiVersion: v1
kind: Service
metadata:
  labels:
    app: jsxjp
  name: jsxjp
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jsxjp
  type: LoadBalancer
